#pragma once
#include <QObject>
#include <QTcpServer>
#include <QTcpSocket>
#include <QMap>
#include <QQueue>
#include <QSet>
#include <QTimer>
#if QT_CONFIG(ssl)
#  include <QSslServer>
#  include <QSslConfiguration>
#  include <QSslCertificate>
#  include <QSslKey>
#endif
#include "ai_client.h"
#include "rag_engine.h"
#include "graph_memory.h"


class LanServer : public QObject {
    Q_OBJECT
public:
    explicit LanServer(AiClient* ai, QObject* parent = nullptr);
    ~LanServer();

    bool    start(quint16 port = 11500);
    void    stop();
    bool    isRunning() const;
    quint16 port()      const;
    int     clientCount() const;
    QStringList connectedIPs() const;

    /** Chiude forzatamente il socket del client con quell'indirizzo IP. */
    void kickClient(const QString& addr);

    /** Imposta il token Bearer (generato dalla UI se vuoto). Auth sempre richiesta se non vuoto. */
    void setAccessToken(const QString& token) { m_accessToken = token; }

    /** Abilita/disabilita TLS self-signed (effetto al prossimo start()). */
    void setTlsEnabled(bool on) { m_tlsRequested = on; }
    bool isTlsEnabled()   const { return m_useTls; }

    /** Imposta l'indirizzo di bind (default AnyIPv4). */
    void setBindAddress(const QHostAddress& addr) { m_bindAddress = addr; }

    /** In modalità headless (--server) /api/launch non ha senso e aprirebbe
     *  terminali sul display del server — disabilitato di default. */
    void setHeadless(bool on) { m_headless = on; }

    /**
     * saveLanToken() / loadLanToken() — persistenza sicura del token LAN.
     *
     * Con HAVE_QKEYCHAIN: usa il keyring di sistema (Secret Service / macOS Keychain /
     * Windows Credential Manager) tramite QKeychain::WritePasswordJob / ReadPasswordJob.
     * Senza HAVE_QKEYCHAIN: fallback a ~/.prismalux/lan_token.key con permessi 0600.
     *
     * Chiamate da LanWanPage (e dall'onboarding) per centralizzare la logica di
     * persistenza senza duplicare la logica keychain in più file.
     */
    static void    saveLanToken(const QString& token);
    static QString loadLanToken();

    /**
     * saveSecret() / loadSecret() / deleteSecret() — storage sicuro generico.
     *
     * Stessa logica di saveLanToken (keyring di sistema con QKeychain, fallback file
     * ~/.prismalux/<key>.key con permessi 0600), ma per una chiave arbitraria.
     * Usato per i segreti dei bot (es. "telegram_token") così non finiscono in
     * QSettings in chiaro.
     */
    static void    saveSecret(const QString& key, const QString& value);
    static QString loadSecret(const QString& key);
    static void    deleteSecret(const QString& key);

    /** Confronto constant-time — evita timing attack sui token Bearer. */
    [[nodiscard]] static bool timingSafeEqual(const QString& a, const QString& b);

    /** Imposta il RagEngine condiviso (opzionale — se nullptr /api/rag ritorna 503). */
    void setRag(RagEngine* rag) { m_rag = rag; }

    /** Imposta la GraphMemory condivisa (opzionale — per /api/graph/*). */
    void setGraphMemory(GraphMemory* gm) { m_graphMemory = gm; }

signals:
    void statusChanged(bool running);
    void clientConnected(const QString& addr, const QString& deviceName);
    void clientDisconnected(const QString& addr);
    void requestHandled(const QString& method, const QString& path, const QString& addr);
    void tokenAutoGenerated(const QString& token);

private slots:
    void onNewConnection();
    void onClientReadyRead();
    void onClientDisconnected();
    void onAiToken(const QString& chunk);
    void onAiFinished(const QString& full);
    void onAiError(const QString& msg);
    void onAiModelsReady(const QStringList& models);
    void onRagEmbeddingReady(const QVector<float>& vec);
    void onRagEmbeddingError(const QString& msg);

    friend struct LlmQueueTestAccess;  ///< accesso test suite a m_llmQueue/broadcastQueuePositions()

private:
    struct Session {
        QTcpSocket* socket        = nullptr;
        QByteArray  buf;
        QString     addr;
        /* HTTP parse state */
        QString     method, path;
        int         contentLength = 0;
        bool        headersDone   = false;
        QByteArray  body;
        QString     authHeader;         ///< valore header Authorization (es. "Bearer TOKEN")
        QString     authHeaderFallback; ///< token estratto da ?token= URL query (scambio cookie)
        QString     cookieSession;      ///< valore cookie p_session= (dopo redirect OTP)
        QString     queryString;        ///< query string grezza (es. "q=sviluppatore&tipo=IT")
        QString     userAgent;          ///< valore header User-Agent del dispositivo
        /* true solo se ha chiamato almeno una API Ollama (non /apk né /) */
        bool        isApiClient   = false;
    };

    void processSession(Session& s);
    void handleTags(Session& s);
    void handleChat(Session& s);
    void handleGenerate(Session& s);
    void handleKnowledge(Session& s);
    void handleRag(Session& s);
    void handleGraphviz(const Session& s);
    void handleWhisper(const Session& s);
    void handleSync(const Session& s);
    void handleMath(QTcpSocket* sock, const Session& s);
    [[nodiscard]] static QString buildMathPythonCode(const QString& action, const QJsonObject& req);
    void handleApk(Session& s);
    void handleIndex(Session& s);
    void handleWebChat(Session& s);
    void handleKatex(Session& s);
    void handleBootstrap(Session& s);
    void handleFileApi(Session& s);
    void handleReplApi(Session& s);
    void handleFinanzaCf(Session& s);
    void handleFinanzaTfr(const Session& s);
    void handleGitApi(const Session& s);
    void handleWikiApi(const Session& s);
    void handleGraphApi(Session& s);
    void sendJson(QTcpSocket* sock, const QByteArray& json);
    void sendStreamLine(const QByteArray& json);
    void sendError(QTcpSocket* sock, int code, const QString& msg);
    void closeStreamSession();
    [[nodiscard]] QByteArray httpOkHeader(const char* contentType) const;
    [[nodiscard]] QByteArray httpStreamHeader() const;
    static void appendAccessLog(const QString& addr, const QString& method, const QString& path);
    /** Genera certificato self-signed in ~/.prismalux/ se non esiste. Ritorna false se openssl non disponibile. */
    [[nodiscard]] static bool _ensureCert(QString& certPath, QString& keyPath);
    [[nodiscard]] bool checkChatRateLimit(Session& s);  ///< true = limit exceeded
    [[nodiscard]] bool checkHeavyRateLimit(Session& s); ///< whisper/graphviz/mcp/launch: max 6/min
    void serveLlmQueue();   ///< serve la prossima richiesta dalla coda LLM
    void onChatRateTimeout();      ///< reset contatore chat rate ogni 60s
    void onKnowledgeRateTimeout(); ///< reset contatore knowledge rate ogni 60s
    void onHeavyRateTimeout();     ///< reset contatore heavy rate ogni 60s

    QHostAddress               m_bindAddress = QHostAddress::AnyIPv4; ///< bind LAN
    bool                       m_headless    = false; ///< true = /api/launch disabilitato
    QTcpServer*                m_server      = nullptr; ///< HTTP plain
#if QT_CONFIG(ssl)
    QSslServer*                m_sslServer   = nullptr; ///< HTTPS self-signed
#endif
    bool                       m_useTls      = false;   ///< true = ascolta su m_sslServer
    bool                       m_tlsRequested = true;   ///< TLS di default; fallback HTTP se openssl mancante
    AiClient*                  m_ai;
    QMap<QTcpSocket*, Session> m_sessions;
    QSet<QString>              m_appClientIps; /* IP unici che hanno usato le API */

    /* Sessione corrente di streaming */
    QTcpSocket* m_streamSock = nullptr;
    bool        m_genMode    = false;

    /* Coda FIFO richieste LLM (multi-utente) */
    struct PendingLlmRequest {
        QPointer<QTcpSocket> sock;
        QString systemPrompt;
        QString userMsg;
        QJsonArray history;
        bool    isGenerate = false;
        QString genPrompt;
        QString genSystem;
        QString model;
    };
    static constexpr int kMaxLlmQueue = 10; ///< max richieste in coda (poi 429)
    QQueue<PendingLlmRequest> m_llmQueue;

    /** Notifica ogni socket ancora in coda della propria posizione aggiornata
     *  (1-based) — scritta come riga NDJSON {"status":"queued","position":N,
     *  "queue_size":M} sulla stessa connessione che riceverà poi lo stream
     *  dei token, i cui header sono già stati inviati all'accodamento
     *  (vedi handleChat/handleGenerate). Chiamata dopo ogni enqueue/dequeue. */
    void broadcastQueuePositions();

    /* Fetch modelli in corso */
    QTcpSocket*             m_tagsSock  = nullptr;
    QMetaObject::Connection m_modelsConn;

    /* RAG: query in corso */
    RagEngine*              m_rag     = nullptr;
    QTcpSocket*             m_ragSock = nullptr;
    int                     m_ragK    = 5;

    /* GraphMemory: borrowed pointer (owned by AgentiMultiPage) */
    GraphMemory*            m_graphMemory = nullptr;

    /* Rate limiting /knowledge: max 10 req/min per IP */
    QMap<QString, int> m_knowledgeReqCount;
    QTimer*            m_knowledgeRateTimer = nullptr;

    /* Rate limiting /api/chat + /api/generate: max 30 req/min per IP */
    QMap<QString, int> m_chatRateCount;
    QTimer*            m_chatRateTimer = nullptr;

    /* Rate limiting endpoint pesanti (whisper/graphviz/mcp/launch): max 6 req/min per IP */
    QMap<QString, int> m_heavyRateCount;
    QTimer*            m_heavyRateTimer = nullptr;

    /* Token di accesso Bearer opzionale (vuoto = nessuna auth richiesta) */
    QString m_accessToken;

    static constexpr int kMaxSessions = 32;  ///< max sessioni TCP simultanee (DoS guard)
};
