#include "tutor_data.h"

SubjectData tutorDataMatematica() {
    return {
        { "📐 MATEMATICA BASE — Fondamenta", {
            { "Algebra ed equazioni", "algebra: equazione ax+b=0 → x=-b/a, sistemi lineari 2×2, disequazioni" },
            { "Funzioni", "funzione f(x): ogni x dà un solo y — dominio, codominio, grafico — composizione, inversa" },
            { "Geometria euclidea", "angoli, area triangolo=base×altezza/2, Pitagora a²+b²=c², cerchio area=πr²" },
            { "Trigonometria", "sin, cos, tan — sin²+cos²=1 — angoli notevoli 30°/45°/60° — usata in grafica e fisica" },
            { "Logaritmi ed esponenziali", "e^x e ln(x) sono inversi — log(a×b)=log(a)+log(b) — base di O(log n)" },
            { "Numeri complessi", "z=a+bi, i²=-1 — modulo |z|=√(a²+b²) — forma polare — formula di Eulero e^(iπ)=-1" },
            { "Combinatoria", "permutazioni P(n,k)=n!/(n-k)!, combinazioni C(n,k) — binomio di Newton" },
        }},
        { "📈 CALCOLO — Analisi matematica", {
            { "Limiti e continuità", "limite lim(x→a) f(x) = L — forme indeterminate 0/0 e ∞/∞ — continuità: grafico senza spazi" },
            { "Derivata — cos'è", "f'(x) = pendenza della tangente in x — velocità istantanea — definizione con limite" },
            { "Regole di derivazione", "x^n → nx^(n-1), sin→cos, cos→-sin, e^x→e^x, ln(x)→1/x — regola della catena" },
            { "Massimi e minimi", "dove f'(x)=0 — f''>0 minimo, f''<0 massimo — studio completo della funzione" },
            { "Integrale indefinito", "∫f(x)dx = antiderivata F(x)+C — per sostituzione e per parti" },
            { "Integrale definito", "∫(a,b)f(x)dx = area algebrica — Teorema Fondamentale: F(b)-F(a)" },
            { "Serie di Taylor", "f(x)=f(a)+f'(a)(x-a)+f''(a)(x-a)²/2!+... — approssimazione polinomiale" },
            { "Equazioni differenziali ODE", "ODE: equazione con f e derivate — separazione variabili — modella crescita, oscillazioni" },
        }},
        { "🔬 MATEMATICA AVANZATA — Algebra lineare e probabilità", {
            { "Vettori", "vettore: direzione e modulo — prodotto scalare a·b=|a||b|cos(θ) — ortogonalità" },
            { "Matrici e sistemi lineari", "matrice: tabella di numeri — moltiplicazione — eliminazione di Gauss — Ax=b" },
            { "Autovalori e autovettori", "Av=λv — diagonalizzazione, PCA in ML, PageRank di Google" },
            { "Calcolo multivariabile", "derivata parziale ∂f/∂x — gradiente ∇f — ottimizzazione ML" },
            { "Probabilità", "P(A)∈[0,1] — variabile aleatoria, valore atteso, varianza — distribuzione normale" },
            { "Statistica", "media, mediana, deviazione standard — correlazione — regressione lineare — p-value" },
            { "Trasformata di Fourier", "FFT: segnale → somma di sinusoidi — applicata in audio, immagini, ML" },
            { "Trasformata di Laplace", "L{f(t)} — trasforma ODE in equazioni algebriche — analisi di stabilità" },
        }},
        { "🔢 ARITMETICA E TEORIA DEI NUMERI", {
            { "Numeri N Z Q R C", "insiemi numerici: naturali, interi, razionali, reali, complessi" },
            { "Divisibilità e MCD", "divisibilità, MCD algoritmo di Euclide, mcm=a*b/MCD" },
            { "Numeri primi", "infinità dei primi, crivello di Eratostene, teorema dei numeri primi" },
            { "Aritmetica modulare", "congruenza a≡b (mod n) — classi Z/nZ — invertibile se MCD(a,n)=1" },
            { "Teorema di Fermat-Eulero", "piccolo teorema di Fermat: a^p≡a (mod p) — φ(n) — Eulero: a^φ(n)≡1" },
            { "Teorema cinese del resto", "sistema di congruenze — soluzione unica mod m₁m₂ — applicazioni in crittografia" },
            { "RSA — teoria dei numeri", "RSA: p,q primi → n=pq, φ(n)=(p-1)(q-1) — cifra con e^s, decifra con d^s" },
        }},
        { "⚙️ METODI NUMERICI", {
            { "Errori numerici", "errore assoluto/relativo — IEEE 754: mantissa, esponente — cancellazione catastrofica" },
            { "Radici di equazioni", "bisezione O(log₂) — Newton-Raphson convergenza quadratica — metodo di Brent" },
            { "Sistemi lineari numerici", "eliminazione gaussiana con pivoting — fattorizzazione LU — metodi iterativi Jacobi" },
            { "Interpolazione", "Lagrange, Newton con differenze divise — spline cubiche — fenomeno di Runge" },
            { "Integrazione numerica", "trapezi O(h²) — Simpson O(h⁴) — Gauss-Legendre — quadratura adattiva" },
            { "ODE numeriche", "Eulero esplicito O(h) — Runge-Kutta RK4 O(h⁴) — metodi impliciti per ODE rigide" },
            { "FFT e segnali", "DFT Xₖ=Σxₙe^(-2πikn/N) — Cooley-Tukey O(N log N) — finestre: Hann, Hamming" },
        }},
        { "🎯 OTTIMIZZAZIONE", {
            { "Programmazione lineare", "max cᵀx s.t. Ax≤b — vertici del poliedro — simplesso — dualità LP" },
            { "Ottimizzazione convessa", "funzione convessa — minimo locale = globale — condizioni KKT — dualità di Lagrange" },
            { "Gradient descent", "xₙ₊₁=xₙ-α∇f(xₙ) — learning rate — momentum, Adam — SGD per ML" },
            { "Teoria dei giochi", "gioco a somma zero — strategia mista — equilibrio di Nash — teorema minimax" },
        }},
    };
}

SubjectData tutorDataFisica() {
    return {
        { "⚙️ MECCANICA CLASSICA — Cinematica e Dinamica", {
            { "Cinematica", "posizione, velocità v=dx/dt, accelerazione a=dv/dt — moto uniformemente accelerato x=x₀+v₀t+½at²" },
            { "Leggi di Newton", "1a: inerzia — 2a: F=ma — 3a: azione-reazione — forza peso P=mg" },
            { "Lavoro ed energia", "W=F·s·cosθ — Ec=½mv² — Ep=mgh — teorema lavoro-energia — conservazione energia" },
            { "Quantità di moto", "p=mv — impulso J=FΔt=Δp — conservazione — urti elastici e anelastici" },
            { "Moto circolare e rotazione", "a_c=v²/r, F_c=mv²/r — angolare: τ=Iα — momento d'inerzia I=Σmᵢrᵢ²" },
            { "Gravitazione universale", "F=Gm₁m₂/r² — G=6.67×10⁻¹¹ — leggi di Keplero: T²∝a³" },
            { "Oscillazioni e MAS", "x=A·cos(ωt+φ) — ω=√(k/m) per molla, ω=√(g/L) per pendolo — risonanza" },
        }},
        { "🌡️ TERMODINAMICA", {
            { "Temperatura e calore", "T (Kelvin) — Q=mcΔT — calore latente — calorimetria" },
            { "Gas ideali", "PV=nRT — Boyle PV=cost — Charles V/T=cost — Gay-Lussac P/T=cost" },
            { "Primo principio", "ΔU=Q-W — isotermo, adiabatico, isobaro, isocoro — W=∫P dV" },
            { "Secondo principio ed entropia", "calore non fluisce da freddo a caldo — ΔS=Q_rev/T ≥ 0 — freccia del tempo" },
            { "Macchine termiche e Carnot", "η=1-Q_c/Q_h — ciclo di Carnot η_C=1-T_c/T_h — frigorifero e pompa di calore" },
            { "Termodinamica statistica", "S=k_B·ln(Ω) — k_B=1.38×10⁻²³ J/K — distribuzione di Boltzmann" },
        }},
        { "⚡ ELETTROMAGNETISMO", {
            { "Elettrostatica", "forza di Coulomb F=kq₁q₂/r² — campo E=F/q — potenziale V=kq/r — energia U=qV" },
            { "Legge di Gauss", "∮E·dA=Q_enc/ε₀ — filo infinito E=λ/(2πε₀r) — piano E=σ/2ε₀" },
            { "Condensatori e circuiti RC", "C=Q/V — energia U=½CV² — circuito RC: τ=RC — carica q(t)=Q(1-e^(-t/τ))" },
            { "Corrente e circuiti", "I=dq/dt — legge di Ohm V=IR — Kirchhoff KVL e KCL — Thevenin" },
            { "Campo magnetico", "forza di Lorentz F=qv×B — Biot-Savart — filo infinito B=μ₀I/(2πr)" },
            { "Induzione elettromagnetica", "legge di Faraday: ε=-dΦ_B/dt — legge di Lenz — induttanza L=Φ/I" },
            { "Equazioni di Maxwell", "∇·E=ρ/ε₀, ∇·B=0, ∇×E=-∂B/∂t, ∇×B=μ₀J+μ₀ε₀∂E/∂t — onde EM" },
            { "Onde elettromagnetiche", "c=3×10⁸ m/s — spettro EM: radio, micro, IR, visibile, UV, X, γ" },
        }},
        { "🌊 ONDE E OTTICA", {
            { "Onde meccaniche", "y=A·sin(kx-ωt) — v=λf — onde stazionarie: nodi e ventri — risonanza" },
            { "Effetto Doppler", "f'=f(v±v_o)/(v∓v_s) — radar, ecografia, redshift cosmologico" },
            { "Ottica geometrica", "riflessione θᵢ=θᵣ — Snell n₁sinθ₁=n₂sinθ₂ — riflessione totale interna" },
            { "Lenti e specchi", "1/f=1/do+1/di — ingrandimento m=-di/do — aberrazioni sferica e cromatica" },
            { "Interferenza e diffrazione", "Young: Δ=d·sinθ=mλ — film sottili — diffrazione — potere risolutivo Rayleigh" },
        }},
        { "⚛️ FISICA MODERNA E RELATIVITÀ", {
            { "Relatività ristretta", "postulati Einstein — dilatazione del tempo γΔt₀ — contrazione L₀/γ — γ=1/√(1-v²/c²)" },
            { "Massa-energia", "E=mc² — energia cinetica Ek=(γ-1)mc² — fotone E=hf, p=h/λ" },
            { "Effetto fotoelettrico", "E_fotone=hf — energia di estrazione φ — prove quantizzazione della luce" },
            { "Dualità onda-particella", "de Broglie λ=h/p — principio di indeterminazione ΔxΔp≥ℏ/2" },
            { "Fisica nucleare", "protoni Z, neutroni N — radioattività α,β,γ — decadimento N=N₀e^(-λt) — T₁/₂" },
            { "Modello Standard", "fermioni (quark, leptoni) e bosoni (γ,W±,Z⁰,g,H) — QED, QCD" },
        }},
        { "🌌 MECCANICA QUANTISTICA", {
            { "Equazione di Schrödinger", "iℏ∂Ψ/∂t=ĤΨ — stazionaria ĤΨ=EΨ — |Ψ|² densità di probabilità" },
            { "Principio di indeterminazione", "Heisenberg: ΔxΔpₓ≥ℏ/2 — non limite tecnico ma fondamentale — tunneling" },
            { "Buca di potenziale", "buca infinita [0,L]: Eₙ=n²π²ℏ²/(2mL²) — energia quantizzata" },
            { "Atomo di idrogeno", "Eₙ=-13.6/n² eV — numeri quantici n,l,m — orbitali s,p,d,f" },
            { "Spin e statistiche", "spin s=½ — Pauli (fermioni) — Fermi-Dirac vs Bose-Einstein" },
            { "Entanglement", "entanglement: stato non-separabile — violazione di Bell — QKD" },
        }},
        { "🔭 ASTROFISICA E COSMOLOGIA", {
            { "Leggi di Keplero", "orbite ellittiche — aree uguali — T²=4π²a³/(GM) — velocità di fuga" },
            { "Stelle e ciclo stellare", "sequenza principale — HR diagram — fusione H→He — nana bianca, supernova, buco nero" },
            { "Buchi neri", "R_s=2GM/c² — orizzonte degli eventi — radiazione di Hawking T_H∝1/M" },
            { "Big Bang", "CMB T=2.725 K — nucleosintesi primordiale — epoche cosmologiche" },
            { "Materia e energia oscura", "materia oscura 27% — energia oscura 68% — equazione di Friedmann" },
        }},
    };
}

SubjectData tutorDataChimica() {
    return {
        { "⚗️ CHIMICA GENERALE E STRUTTURA ATOMICA", {
            { "Struttura atomica", "modelli: Thomson, Rutherford, Bohr, Schrödinger — numero atomico Z, massa A, isotopi" },
            { "Tavola periodica", "periodi e gruppi — raggio atomico, elettronegatività, energia di ionizzazione" },
            { "Legami chimici", "ionico: trasferimento e⁻ — covalente: condivisione — metallico — Van der Waals — VSEPR" },
            { "Nomenclatura IUPAC", "ossidi, idrossidi, acidi ossigenati, sali — organici: -ano, -ene, -olo, -oico" },
            { "Stechiometria", "bilanciamento — mole n=m/M — reagente limitante — resa percentuale — titolazione" },
            { "Soluzioni e concentrazione", "molarità M=mol/L — proprietà colligative — legge di Raoult" },
        }},
        { "🧪 CHIMICA INORGANICA", {
            { "Acidi e basi", "Arrhenius, Brønsted-Lowry, Lewis — coppie coniugate — Ka, Kb" },
            { "pH e soluzioni tampone", "pH=-log[H⁺] — acido forte vs debole — Henderson-Hasselbalch: pH=pKa+log([A⁻]/[HA])" },
            { "Reazioni di precipitazione", "Ksp=[M^n+][X^m-] — Q vs Ksp — effetto ione comune" },
            { "Composti di coordinazione", "ione centrale + ligandi — numero di coordinazione — isomeria cis-trans" },
            { "Elettrochimica inorganica", "E° — serie elettrochimica — corrosione — protezione catodica" },
        }},
        { "🧬 CHIMICA ORGANICA", {
            { "Idrocarburi", "alcani CₙH₂ₙ₊₂ (sp³) — alcheni (sp²) — alchini (sp) — aromatici (Hückel 4n+2)" },
            { "Gruppi funzionali", "alcoli -OH, aldeidi -CHO, chetoni C=O, acidi -COOH, esteri, ammine, amidi" },
            { "Isomeria", "costituzionale — stereoisomeria: geometrica (cis-trans), ottica (carbonio chirale, enantiomeri)" },
            { "Meccanismi SN e E", "SN2: inversione Walden — SN1: carbocatione, racemizzazione — E2 antiperiplanare" },
            { "Reazioni di addizione", "addizione elettrofila: HX (Markovnikov), H₂ (Pd), H₂O — addizione nucleofila a carbonile" },
            { "Chimica aromatica", "SEAr: nitrazione, alogenazione, Friedel-Crafts — attivatori vs disattivatori" },
            { "Polimeri", "addizione: PE, PP, PVC — condensazione: nylon, PET — Tg e Tm" },
        }},
        { "🔬 BIOCHIMICA", {
            { "Aminoacidi e proteine", "20 aminoacidi — legame peptidico — struttura 1°,2°(α-elica,β-foglietto),3°,4°" },
            { "Enzimi e catalisi", "sito attivo — Michaelis-Menten: v=Vmax[S]/(Km+[S]) — inibitori — coenzimi" },
            { "Carboidrati", "glucosio C₆H₁₂O₆ — disaccaridi: saccarosio — polisaccaridi: amido, glicogeno, cellulosa" },
            { "Acidi nucleici DNA RNA", "basi: purine (A,G), pirimidine (C,T,U) — doppia elica Watson-Crick — mRNA, tRNA, rRNA" },
            { "Metabolismo energetico", "glicolisi → piruvato +2ATP — Krebs — catena respiratoria — totale ~30 ATP per glucosio" },
        }},
        { "⚡ CHIMICA FISICA", {
            { "Termochimica", "ΔH°rxn=ΣΔH°f(prod)-ΣΔH°f(reag) — legge di Hess — energia di legame" },
            { "Energia libera di Gibbs", "ΔG=ΔH-TΔS — spontanea se ΔG<0 — ΔG°=-RT·ln K" },
            { "Equilibrio chimico", "Kc=[prod]^ν/[reag]^ν — Kp=Kc(RT)^Δn — principio di Le Chatelier" },
            { "Cinetica chimica", "r=k[A]^α[B]^β — ordini — Arrhenius k=A·e^(-Ea/RT) — catalisi" },
            { "Elettrochimica", "cella di Daniell — Nernst E=E°-(RT/nF)ln Q — ΔG=-nFE° — elettrolisi" },
            { "Spettroscopia chimica", "IR: stretching/bending — NMR: chemical shift δ(ppm) — UV-Vis — spettrometria di massa" },
        }},
        { "📊 CHIMICA ANALITICA", {
            { "Titolazioni", "acido-base — indicatori — titolazione con buffer — retrotitolazione" },
            { "Cromatografia", "GC: carrier He — HPLC: C18 reversed phase — TLC — fattore di ritenzione Rf" },
            { "Errori e validazione", "sistematici (accuratezza) vs casuali (precisione) — LOD, LOQ — linearità" },
            { "Chimica ambientale", "DBO, COD — metalli pesanti — PM10, PM2.5, SO₂, NOₓ — trattamento acque" },
        }},
        { "🌱 CHIMICA VERDE", {
            { "12 Principi della chimica verde", "Anastas & Warner — prevenzione, atomo efficiency, catalisi, energie rinnovabili" },
            { "Solventi verdi", "CO₂ supercritico (Tc=31°C) — acqua come solvente — DES (deep eutectic solvents)" },
            { "Catalisi sostenibile", "enzimatica — organocatalisi — fotoredox — metalli abbondanti Fe,Co,Cu vs Pd,Rh" },
            { "Chimica atmosferica", "ozono: O₃+hν→O₂+O — CFC — effetto serra CO₂,CH₄ — smog fotochimico NOₓ+VOC" },
        }},
    };
}

SubjectData tutorDataSicurezza() {
    return {
        { "🔒 SICUREZZA INFORMATICA ENTERPRISE", {
            { "OWASP Top 10", "10 vulnerabilità critiche: injection, broken auth, XSS, IDOR, SSRF, XXE, dati esposti, logging assente" },
            { "SQL Injection", "WHERE 1=1 bypass auth — parameterized query — blind SQLi, time-based, error-based, second-order" },
            { "XSS Cross-Site Scripting", "reflected (URL), stored (DB), DOM-based — CSP header, escape output, DOMPurify" },
            { "CSRF", "Cross-Site Request Forgery — CSRF token, SameSite=Strict cookie, origin header check" },
            { "Crittografia simmetrica", "AES 128 bit blocchi, chiavi 128/192/256 bit — modalità CBC, GCM autenticata" },
            { "Crittografia asimmetrica", "RSA: pubblica cifra, privata decifra — 2048/4096 bit — firma digitale, X.509" },
            { "Hashing e Salt", "bcrypt/argon2: hash lento e salato — rainbow table inutili — cost factor regolabile" },
            { "Penetration Testing", "workflow: recon → scanning (nmap) → exploitation → post-expl → reporting — CVSS scoring" },
            { "Zero Trust", "'non fidarti mai, verifica sempre' — micro-segmentazione, least privilege, MFA" },
            { "CTF Capture The Flag", "categorie: web, crypto, pwn, reversing, forensics — pwntools, ghidra, burp suite" },
            { "Vulnerability Management", "CVE, CVSS score (0-10) — patch management, responsible disclosure, bug bounty" },
        }},
        { "🐧 LINUX ENTERPRISE — Amministrazione avanzata", {
            { "Filesystem Hierarchy FHS", "/bin eseguibili, /etc config, /var dati, /proc kernel virtuale, /sys hardware" },
            { "Permessi e ACL", "chmod 755 = rwxr-xr-x — setuid, setgid, sticky bit — ACL con setfacl/getfacl" },
            { "Processi e Segnali", "ps aux, top, htop — kill -15 SIGTERM (graceful), kill -9 SIGKILL — nice/renice" },
            { "Systemd e servizi", "systemctl start/stop/enable — journalctl -u servizio -f — unit file in /etc/systemd/" },
            { "Networking Linux", "ip addr show, ip route, ss -tlnp — tcpdump — NetworkManager — bridge, bond, vlan" },
            { "Bash scripting avanzato", "array ${arr[@]}, funzioni, getopts — subshell $(cmd) — trap — set -euo pipefail" },
            { "SSH hardening", "sshd_config: PermitRootLogin no, PasswordAuthentication no — fail2ban — ed25519" },
            { "iptables e nftables", "catene INPUT/OUTPUT/FORWARD — stateful con conntrack — nftables — ufw frontend" },
            { "Docker e container", "run/build/push/compose — Dockerfile: FROM, RUN, COPY — namespace, cgroup — rootless" },
            { "Ansible automazione", "playbook YAML, inventory, roles, handlers — idempotente — agentless via SSH" },
        }},
        { "🌐 PROTOCOLLI DI RETE", {
            { "Modello OSI", "7 strati: fisico, datalink, rete, trasporto, sessione, presentazione, applicazione" },
            { "TCP vs UDP", "TCP (affidabile, ordinato) vs UDP (veloce, senza garanzie) — scegli TCP per dati, UDP per streaming" },
            { "IP e Subnetting", "192.168.1.10 — 4 ottetti — CIDR /24 = 256 host — subnet mask, broadcast" },
            { "HTTP e HTTPS", "GET, POST, PUT, PATCH, DELETE — status code: 200, 404, 500 — HTTPS = HTTP su TLS" },
            { "DNS", "risolve nomi in IP — query ricorsiva: browser → resolver → root → TLD → authoritative — TTL" },
            { "TLS e SSL", "handshake: client hello → certificato → chiave pubblica → session key simmetrica" },
            { "REST API", "risorse come URL, verbi HTTP corretti, stateless, JSON — non REST se stato nel server" },
            { "OAuth2 e JWT", "OAuth2: delega autorizzazione — JWT: header.payload.signature in base64" },
            { "WebSocket", "full-duplex persistente su TCP — upgrade da HTTP — ideale per chat, giochi, notifiche" },
            { "gRPC e Protocol Buffers", "RPC su HTTP/2 — protobuf: schema binario tipizzato, 10× più compatto di JSON" },
            { "SSH — Secure Shell", "connessione cifrata — chiave pubblica/privata RSA/Ed25519 — port forwarding, SCP" },
        }},
        { "🖥️ VIRTUALIZZAZIONE", {
            { "Hypervisor tipo 1 e 2", "tipo 1 bare-metal: ESXi, Proxmox, Hyper-V — tipo 2 hosted: VirtualBox, VMware Workstation" },
            { "Proxmox VE", "KVM per VM, LXC per container — web UI :8006 — storage ZFS, LVM, Ceph — backup vzdump" },
            { "VMware ESXi e vSphere", "ESXi tipo 1 — vCenter gestione centralizzata — vMotion migrazione live — HA, DRS" },
            { "KVM e QEMU", "KVM nel kernel Linux — QEMU emulatore — virtio driver paravirtualizzati 10× più veloci" },
            { "Container vs VM", "VM: isolamento completo, kernel proprio, GB — container: condividono kernel, MB — Docker/LXC" },
            { "Alta disponibilità HA", "cluster HA: VM si riavvia su altro nodo — fencing STONITH — shared storage — quorum" },
        }},
    };
}

SubjectData tutorDataInformatica() {
    return {
        { "🟢 BASI — Primo approccio Python", {
            { "Variabili", "variabili Python: int str float bool, assegnazione, scope" },
            { "if / else", "if else Python: condizioni, operatori di confronto, elif" },
            { "Ciclo for", "ciclo for Python: iterare su lista e range(), iteratori" },
            { "Ciclo while", "ciclo while Python: quando usarlo, condizione, loop infinito" },
            { "Funzioni", "funzioni Python: def, parametri, return, perché usarle" },
            { "Liste", "liste Python: append, pop, accesso per indice, len(), slicing" },
            { "Dizionari", "dizionari Python: coppie chiave-valore, creare, leggere, aggiornare" },
        }},
        { "🔵 FONDAMENTALI — Python solido", {
            { "Stringhe e metodi", "upper lower split join strip replace, f-string, encoding" },
            { "Tuple", "tuple Python: immutabilità, differenza da lista, quando usarle" },
            { "Set", "set Python: senza duplicati, add, union, intersection, difference" },
            { "Slicing", "lista[1:4], lista[::-1], stringa[2:5], step, copia con [:]" },
            { "f-string", "formattazione con variabili, espressioni, formato numeri, padding" },
            { "try / except", "try except finally raise, tipi di eccezione, best practices" },
            { "File: leggere/scrivere", "open() read write append, with statement, encoding utf-8" },
            { "Import e moduli", "import, from import, as, moduli standard os sys math random" },
        }},
        { "🟡 INTERMEDIO — Python fluente", {
            { "List comprehension", "[x*2 for x in lista if x>0], quando usarla vs ciclo for" },
            { "Dict comprehension", "{k:v for k,v in ...}, uso pratico, leggibilità" },
            { "enumerate() e zip()", "indice+valore, unire due liste, esempi pratici" },
            { "sorted() e key=", "ordinare lista, key=lambda, reverse=True, ordinare oggetti" },
            { "lambda", "funzione anonima in una riga, quando usarla, limiti" },
            { "map() e filter()", "trasformare e filtrare liste senza ciclo for" },
            { "*args e **kwargs", "funzione con numero variabile di argomenti, unpacking" },
            { "Argomenti default", "il bug classico con liste come default, oggetti mutabili" },
            { "Closures", "funzione che ricorda variabili del contesto esterno, free variables" },
        }},
        { "🟠 CLASSI — Programmazione a Oggetti", {
            { "Classi e oggetti", "cos'è una classe, oggetto, istanza, attributo, metodo" },
            { "self e __init__", "costruttore, inizializzazione attributi, self spiegato bene" },
            { "Ereditarietà", "classe figlia estende padre, super(), override, MRO" },
            { "Metodi speciali", "__str__ __repr__ __len__ __eq__ __add__, dunder methods" },
            { "@property", "getter setter senza metodi, attributo calcolato, @property.setter" },
            { "@staticmethod/@classmethod", "metodo senza self, metodo di classe, quando usarli" },
            { "Composizione vs ereditarietà", "has-a invece di is-a, quando preferire composizione" },
        }},
        { "🔴 AVANZATO — Python esperto", {
            { "Generatori e yield", "yield, lazy evaluation, memoria, confronto con lista" },
            { "Decoratori", "@decorator, funzione che modifica funzione, esempi pratici" },
            { "Context manager", "with statement, __enter__ __exit__, creare il proprio" },
            { "Mutabilità e riferimenti", "y=x non copia, id(), oggetti mutabili vs immutabili" },
            { "is vs ==", "identità vs uguaglianza, quando usare quale, trappole comuni" },
            { "Shallow vs deep copy", "copy.copy vs copy.deepcopy, il problema con oggetti annidati" },
            { "Type hints", "def foo(x: int) -> str, typing, vantaggi, mypy" },
            { "Dataclasses", "@dataclass: __init__ __repr__ automatici, field()" },
        }},
        { "💻 PYTHON TECNICO", {
            { "Threading e GIL", "thread, GIL Global Interpreter Lock, threading vs multiprocessing" },
            { "async / await", "coroutine, asyncio, event loop, differenza da thread" },
            { "Regular expressions", "re.match re.search re.findall, pattern comuni, gruppi" },
            { "Memory management", "garbage collector, reference counting, gc module, memory leak" },
            { "Design patterns", "Singleton Factory Observer Strategy, esempi pratici Python" },
            { "Profiling", "cProfile timeit line_profiler, colli di bottiglia, ottimizzare" },
        }},
        { "✨ CLEAN CODE E SOLID", {
            { "Nomi significativi", "variabili e funzioni devono dire cosa fanno senza commenti" },
            { "Funzioni brevi", "una funzione = un solo compito, max 20 righe" },
            { "DRY", "Don't Repeat Yourself: ogni conoscenza ha un solo posto nel codice" },
            { "KISS", "Keep It Simple Stupid: la soluzione più semplice che funziona" },
            { "S — Single Responsibility", "ogni classe o funzione ha una sola ragione per cambiare" },
            { "O — Open/Closed", "aperto all'estensione, chiuso alla modifica" },
            { "L — Liskov Substitution", "classe figlia sostituisce padre senza sorprese" },
            { "I — Interface Segregation", "interfacce piccole e specifiche, non una grande" },
            { "D — Dependency Inversion", "dipendi da astrazioni, non da implementazioni concrete" },
        }},
        { "🧪 TESTING E ARCHITETTURA", {
            { "Unit test con pytest", "testa una funzione alla volta, casi normali e casi limite" },
            { "TDD", "Test Driven Development: scrivi il test prima del codice — red, green, refactor" },
            { "Mocking", "unittest.mock: sostituisci dipendenze esterne nei test con oggetti finti" },
            { "MVC pattern", "Model-View-Controller: dati, interfaccia e logica separati" },
            { "REST API design", "risorse come URL, verbi HTTP corretti, status code, versioning" },
            { "CAP Theorem", "Consistency, Availability, Partition tolerance: puoi averne solo 2" },
            { "Caching strategico", "cache in memoria, Redis, invalidazione corretta, N+1 problem" },
            { "Git workflow", "feature branch, commit atomici, messaggi chiari, pull request" },
        }},
    };
}

SubjectData tutorDataAlgoritmi() {
    return {
        { "⚡ ALGORITMI BASE", {
            { "Bubble Sort", "confronta vicini, scambia, ripeti — O(n²) — in-place, stabile" },
            { "Selection Sort", "trova il minimo, mettilo in testa, ripeti — O(n²)" },
            { "Insertion Sort", "prendi elemento, inseriscilo nel posto giusto — O(n²), O(n) best" },
            { "Ricerca Lineare", "controlla ogni elemento uno a uno — O(n) — funziona su qualsiasi lista" },
            { "Ricerca Binaria", "lista ordinata, dividi a metà — O(log n) — iterativa e ricorsiva" },
            { "Ricorsione", "funzione che chiama se stessa, caso base, stack di chiamate" },
            { "Complessità O(n)", "O(1) O(n) O(n²) O(log n) O(n log n) in parole semplici" },
        }},
        { "🔥 ALGORITMI AVANZATI", {
            { "Merge Sort", "dividi la lista a metà, ordina le metà, fondi — O(n log n), stabile" },
            { "Quick Sort", "scegli pivot, partiziona, ricorsione — O(n log n) medio, O(n²) worst" },
            { "Stack e Queue", "Stack LIFO, Queue FIFO — deque, append, pop, popleft — usi pratici" },
            { "Alberi binari", "nodo con figlio sinistro/destro, visita in-order pre-order post-order" },
            { "Grafi: BFS e DFS", "BFS visita per livelli (coda), DFS visita in profondità (stack)" },
            { "Programmazione dinamica", "memoization, tabulation, zaino, Fibonacci — O(n) vs O(2^n)" },
            { "Hashing", "come funziona dict e set internamente, collision, hash(), amortized O(1)" },
        }},
        { "💎 ALGORITMI ENTERPRISE", {
            { "Heap / Priority Queue", "heapq module, min-heap — trova K elementi maggiori in O(n log k)" },
            { "Dijkstra shortest path", "percorso più breve in grafo pesato non-negativo — O((V+E) log V)" },
            { "Union-Find (DSU)", "componenti connesse, rilevamento cicli — O(α(n)) quasi costante" },
            { "LRU Cache O(1)", "Least Recently Used con OrderedDict — get e put in O(1) — FAANG" },
            { "Sliding Window", "subarray con condizione — trasforma O(n²) in O(n)" },
            { "Two Pointers", "due indici che si avvicinano — coppia con somma target, palindromo" },
            { "Segment Tree", "query range (min, max, somma) in O(log n) — update O(log n)" },
            { "Backtracking", "prova tutte le soluzioni, torna indietro se fallisce — N-Regine, Sudoku" },
        }},
        { "🧩 PROGRAMMAZIONE DINAMICA", {
            { "Zaino 0/1", "ogni oggetto si prende intero o si lascia — dp[i][w] = max valore" },
            { "Coin Change", "minimo numero di monete — dp[i] = min(dp[i-moneta]+1)" },
            { "LCS", "Longest Common Subsequence — dp[i][j] da confronto s1[i] e s2[j]" },
            { "Edit Distance", "minimo operazioni (insert/delete/replace) — Levenshtein — spell check" },
            { "LIS", "Longest Increasing Subsequence — dp[i]=1+max(dp[j]) con j<i" },
            { "Memoization vs Tabulation", "top-down ricorsiva vs bottom-up iterativa — pro e contro" },
        }},
        { "🌐 GRAFI AVANZATI", {
            { "Bellman-Ford", "percorso minimo anche con pesi negativi — rilassa tutti gli archi V-1 volte" },
            { "Floyd-Warshall", "tutti i percorsi minimi tra tutte le coppie — O(V³) — intermediario k" },
            { "Kruskal MST", "Minimum Spanning Tree — ordina archi, aggiungili se non creano ciclo" },
            { "A* Search", "ricerca con euristica f(n)=g(n)+h(n) — più veloce di Dijkstra — GPS" },
            { "Topological Sort", "ordine lineare di un DAG — Kahn (BFS) o DFS con stack" },
            { "Componenti Fortemente Connesse", "SCC: Tarjan o Kosaraju — sottografi dove ogni nodo raggiunge ogni altro" },
        }},
        { "💛 GREEDY E BACKTRACKING", {
            { "Activity Selection", "massimo attività non sovrapposte — ordina per fine, scegli disponibile" },
            { "Huffman Coding", "compressione ottimale — frequenze → albero binario — ZIP, PNG" },
            { "N-Queens", "N regine su scacchiera N×N — backtracking colonna per colonna" },
            { "Sudoku Solver", "per ogni cella vuota prova 1-9 — torna indietro se impossibile" },
            { "Permutazioni", "genera tutte le N! permutazioni — ricorsione + swap + backtrack" },
            { "Subset Sum", "esistono elementi che sommano a target — backtracking o DP" },
        }},
        { "🔢 ALGORITMI MATEMATICI", {
            { "GCD — Euclide", "MCD(a,b)=MCD(b,a%b) — O(log min(a,b)) — base di RSA e frazioni" },
            { "Potenza Modulare", "b^e mod m in O(log e) — fondamentale in RSA" },
            { "Miller-Rabin", "test probabilistico di primalità in O(k log²n) — per chiavi RSA" },
            { "Crivo di Eratostene", "trova tutti i primi ≤ n in O(n log log n) — segna i multipli" },
            { "FFT Fast Fourier Transform", "converte segnale tempo→frequenza in O(n log n) — moltiplicazione polinomi" },
        }},
        { "🏗️ STRUTTURE DATI AVANZATE", {
            { "AVL Tree", "BST auto-bilanciato con rotazioni — ricerca/insert/delete O(log n) garantiti" },
            { "Red-Black Tree", "BST bilanciato con proprietà colore — usato in std::map C++" },
            { "B-Tree", "albero bilanciato per database — minimizza accessi disco" },
            { "Segment Tree", "range query O(log n) — update O(log n) — più flessibile di Fenwick" },
            { "Fenwick Tree BIT", "prefix sum aggiornabili in O(log n) — usa bit meno significativo" },
            { "Skip List", "lista con livelli multipli — ricerca O(log n) medio — alternativa ad AVL" },
        }},
    };
}
