"""
tutor_dati.py
=============
Dati del Tutor AI: argomenti per materia.
Nessuna logica — solo liste di (nome, descrizione) per ogni sezione.

Importato da tutor_semplice.py.
"""

SEZIONI_ARGOMENTI = [
    ("🟢 BASI — Primo approccio Python", [
        ("Variabili",              "variabili Python: cosa sono, int str float bool, assegnazione"),
        ("if / else",              "if else Python: condizioni, operatori di confronto, elif"),
        ("Ciclo for",              "ciclo for Python: iterare su lista e range(), cosa significa iterare"),
        ("Ciclo while",            "ciclo while Python: quando usarlo, condizione, loop infinito"),
        ("Funzioni",               "funzioni Python: def, parametri, return, perché usarle"),
        ("Liste",                  "liste Python: creare, append, pop, accesso per indice, len()"),
        ("Dizionari",              "dizionari Python: coppie chiave-valore, creare, leggere, aggiornare"),
    ]),
    ("🔵 FONDAMENTALI — Python solido", [
        ("Stringhe e metodi",      "stringhe Python: upper lower split join strip replace, f-string"),
        ("Tuple",                  "tuple Python: cosa sono, differenza da lista, immutabilità, quando usarle"),
        ("Set",                    "set Python: insieme senza duplicati, add, union, intersection, difference"),
        ("Slicing",                "slicing Python: lista[1:4], lista[::-1], stringa[2:5], step"),
        ("f-string",               "f-string Python: formattazione stringhe con variabili, espressioni, formato numeri"),
        ("None",                   "None Python: cosa significa, confronto con is None, valore opzionale"),
        ("Operatori logici",       "operatori logici Python: and or not, tabella di verità, short-circuit"),
        ("try / except",           "gestione errori Python: try except finally raise, tipi di eccezione"),
        ("File: leggere/scrivere", "file Python: open() read write append, with statement, encoding utf-8"),
        ("Import e moduli",        "import Python: import, from import, as, moduli standard os sys math random"),
    ]),
    ("🟡 INTERMEDIO — Python fluente", [
        ("List comprehension",     "list comprehension Python: [x*2 for x in lista if x>0], quando usarla"),
        ("Dict comprehension",     "dict comprehension Python: {k:v for k,v in ...}, uso pratico"),
        ("enumerate() e zip()",    "enumerate() e zip() Python: indice+valore, unire due liste, esempi pratici"),
        ("sorted() e key=",        "sorted() Python: ordinare lista, key=lambda, reverse=True, ordinare oggetti"),
        ("lambda",                 "funzione lambda Python: funzione anonima in una riga, quando usarla"),
        ("map() e filter()",       "map() filter() Python: trasformare e filtrare liste senza ciclo for"),
        ("*args e **kwargs",       "*args **kwargs Python: funzione con numero variabile di argomenti"),
        ("Argomenti default ⚠️",   "argomenti default mutabili Python: il bug classico con liste come default"),
        ("Scope: locale/globale",  "scope Python: variabile locale, globale, global keyword, nonlocal"),
        ("Closures",               "closures Python: funzione che ricorda variabili del contesto esterno"),
    ]),
    ("🟠 CLASSI — Programmazione a Oggetti", [
        ("Classi e oggetti",       "classi Python: cos'è una classe, oggetto, istanza, attributo"),
        ("self e __init__",        "self e __init__ Python: costruttore, inizializzazione attributi, self spiegato"),
        ("Ereditarietà",           "ereditarietà Python: classe figlia estende classe padre, super(), override"),
        ("Metodi speciali",        "metodi speciali Python: __str__ __repr__ __len__ __eq__ __add__, dunder methods"),
        ("@property",              "@property Python: getter setter senza metodi, attributo calcolato"),
        ("@staticmethod/@classmethod", "@staticmethod @classmethod Python: metodo senza self, metodo di classe, quando usarli"),
        ("Composizione vs ereditarietà", "composizione vs ereditarietà Python: quando usare has-a invece di is-a"),
    ]),
    ("🔴 AVANZATO — Python esperto", [
        ("Generatori e yield",     "generatori Python: yield, lazy evaluation, memoria, confronto con lista"),
        ("Decoratori",             "decoratori Python: @decorator, funzione che modifica funzione, esempi pratici"),
        ("Context manager",        "context manager Python: with statement, __enter__ __exit__, creare il proprio"),
        ("Mutabilità e riferimenti","mutabilità Python: y=x non copia, id(), oggetti mutabili vs immutabili"),
        ("is vs ==",               "is vs == Python: identità vs uguaglianza, quando usare quale, trappole comuni"),
        ("Shallow vs deep copy",   "shallow copy e deep copy Python: copy.copy vs copy.deepcopy, il problema con oggetti annidati"),
        ("Type hints",             "type hints Python: def foo(x: int) -> str, typing, vantaggi, mypy"),
        ("Dataclasses",            "@dataclass Python: classe dati automatica, __init__ __repr__ automatici, field()"),
        ("ABC e Protocol",         "Abstract Base Class Python: abc.ABC, @abstractmethod, Protocol, duck typing"),
        ("Iteratori",              "iteratori Python: __iter__ __next__, iter(), next(), differenza da generatore"),
    ]),
    ("⚡ ALGORITMI BASE", [
        ("Bubble Sort",            "algoritmo Bubble Sort: confronta vicini, scambia, ripeti — O(n²)"),
        ("Selection Sort",         "algoritmo Selection Sort: trova il minimo, mettilo in testa, ripeti — O(n²)"),
        ("Insertion Sort",         "algoritmo Insertion Sort: prendi elemento, inseriscilo nel posto giusto — O(n²)"),
        ("Ricerca Lineare",        "ricerca lineare: controlla ogni elemento uno a uno dall'inizio — O(n)"),
        ("Ricerca Binaria",        "ricerca binaria: lista ordinata, dividi a metà, vai nella metà giusta — O(log n)"),
        ("Ricorsione",             "ricorsione Python: funzione che chiama se stessa, caso base, stack di chiamate"),
        ("Complessità O(n)",       "complessità algoritmica O(1) O(n) O(n²) O(log n) O(n log n) in parole semplici"),
    ]),
    ("🔥 ALGORITMI AVANZATI", [
        ("Merge Sort",             "Merge Sort: dividi la lista a metà, ordina le metà, fondi — O(n log n)"),
        ("Quick Sort",             "Quick Sort: scegli pivot, partiziona, ricorsione — O(n log n) medio"),
        ("Stack e Queue",          "Stack (LIFO) e Queue (FIFO) Python: deque, append, pop, popleft, usi pratici"),
        ("Alberi binari",          "albero binario Python: nodo con figlio sinistro/destro, visita in-order pre-order"),
        ("Grafi: BFS e DFS",       "grafi Python: nodi e archi, BFS visita per livelli, DFS visita in profondità"),
        ("Programmazione dinamica","programmazione dinamica Python: memoization, tabulation, problema dello zaino, Fibonacci"),
        ("Hashing",                "hashing Python: come funziona dict e set internamente, collision, hash()"),
    ]),
    ("💻 PYTHON TECNICO — livello avanzato", [
        ("Threading e GIL",        "threading Python: thread, GIL Global Interpreter Lock, quando usare threading vs multiprocessing"),
        ("async / await",          "async await Python: coroutine, asyncio, event loop, differenza da thread"),
        ("Regular expressions",    "regular expressions Python: re.match re.search re.findall, pattern comuni"),
        ("Memory management",      "memory management Python: garbage collector, reference counting, gc module, memory leak"),
        ("Design patterns",        "design patterns Python: Singleton Factory Observer Strategy, esempi pratici"),
        ("Profiling",              "profiling Python: cProfile timeit line_profiler, trovare colli di bottiglia, ottimizzare"),
        ("Metaclassi",             "metaclassi Python: class è un oggetto, type, __new__ vs __init__, quando servono"),
    ]),
    ("🧠 MENTALITÀ DEL PROGRAMMATORE", [
        ("Pensiero computazionale", "pensiero computazionale: scomporre il problema in passi piccoli prima di scrivere codice"),
        ("Decomposizione",          "decomposizione del problema: dividere un problema grande in sotto-problemi indipendenti"),
        ("Debugging sistematico",   "debugging sistematico: riproduci il bug, isola la causa, forma ipotesi, verifica — non indovinare"),
        ("Lettura del codice",      "leggere codice altrui: capire prima di modificare, tracciare il flusso, cercare l'intenzione"),
        ("Imparare dagli errori",   "imparare dagli errori: ogni bug è una lezione — documenta cosa hai sbagliato e perché"),
        ("Pensiero da tester",      "pensiero da tester: chiedi sempre 'cosa potrebbe andare storto?' prima di rilasciare codice"),
        ("Chiedere aiuto bene",     "chiedere aiuto efficace: minimal reproducible example, cosa hai provato, cosa ti aspetti"),
        ("Rubber duck debugging",   "rubber duck debugging: spiega il tuo codice ad alta voce — spesso trovi il bug da solo"),
        ("Gestire la complessità",  "gestire la complessità: tieni le cose semplici, aggiungi complessità solo quando necessaria"),
    ]),
    ("✨ CLEAN CODE — Codice leggibile", [
        ("Nomi significativi",      "nomi significativi: variabili e funzioni devono dire cosa contengono/fanno senza commenti"),
        ("Funzioni brevi",          "funzioni brevi e focalizzate: una funzione = un solo compito, max 20 righe idealmente"),
        ("DRY",                     "DRY Don't Repeat Yourself: se copi-incolli codice, crea una funzione — ogni conoscenza ha un solo posto"),
        ("KISS",                    "KISS Keep It Simple Stupid: la soluzione più semplice che funziona è quella giusta"),
        ("YAGNI",                   "YAGNI You Aren't Gonna Need It: non scrivere codice per esigenze future immaginarie"),
        ("Commenti utili",          "commenti utili vs inutili: spiega il perché, non il cosa — il codice dice già il cosa"),
        ("Code smell",              "code smell: segnali che il codice va migliorato — funzione troppo lunga, troppi parametri, duplicazione"),
        ("Refactoring",             "refactoring: migliorare la struttura del codice senza cambiarne il comportamento esterno"),
        ("Magic numbers",           "magic numbers: evita numeri e stringhe letterali nel codice — usa costanti con nome"),
    ]),
    ("🏗️ SOLID — Principi di design", [
        ("S — Single Responsibility","Single Responsibility Principle: ogni classe o funzione ha una sola ragione per cambiare"),
        ("O — Open/Closed",         "Open/Closed Principle: aperto all'estensione, chiuso alla modifica — aggiungi, non toccare"),
        ("L — Liskov Substitution", "Liskov Substitution Principle: una classe figlia deve poter sostituire la classe padre senza sorprese"),
        ("I — Interface Segregation","Interface Segregation Principle: interfacce piccole e specifiche, non una grande che fa tutto"),
        ("D — Dependency Inversion","Dependency Inversion Principle: dipendi da astrazioni, non da implementazioni concrete"),
        ("Separation of Concerns",  "separation of concerns: ogni modulo si occupa di una sola cosa — logica, dati, interfaccia separate"),
        ("Dependency Injection",    "dependency injection Python: passa le dipendenze dall'esterno invece di crearle dentro la funzione"),
    ]),
    ("🧪 TESTING — Codice affidabile", [
        ("Unit test con pytest",    "unit test Python con pytest: testa una funzione alla volta, casi normali e casi limite"),
        ("TDD",                     "TDD Test Driven Development: scrivi il test prima del codice — red, green, refactor"),
        ("Test di integrazione",    "test di integrazione: verifica che più componenti funzionino bene insieme"),
        ("Mocking",                 "mocking Python con unittest.mock: sostituisci dipendenze esterne nei test con oggetti finti"),
        ("Fixtures e parametrize",  "pytest fixtures e parametrize: dati di test riutilizzabili, stessa funzione testata con valori diversi"),
        ("Code coverage",           "code coverage Python: coverage.py misura quali righe vengono eseguite dai tuoi test"),
        ("Assert e eccezioni",      "pytest.raises: verifica che il codice lanci le eccezioni giuste nelle condizioni giuste"),
        ("Test leggibili",          "test leggibili: nome del test = descrizione del comportamento atteso — test_somma_due_negativi"),
    ]),
    ("🏢 ARCHITETTURA ENTERPRISE", [
        ("Layered architecture",    "architettura a strati: presentation, business logic, data access — ogni strato parla solo con quello adiacente"),
        ("Repository pattern",      "repository pattern: separa la logica di accesso al database dal resto del codice"),
        ("MVC pattern",             "MVC Model-View-Controller: separa dati, interfaccia e logica — ogni parte cambia indipendentemente"),
        ("Service layer",           "service layer: logica di business in classi service separate dai controller e dai modelli"),
        ("DTO e Value Object",      "DTO Data Transfer Object: oggetti semplici per trasportare dati tra strati senza logica"),
        ("Event-driven",            "event-driven architecture: componenti comunicano tramite eventi — disaccoppiamento massimo"),
        ("Microservizi vs monolite","microservizi vs monolite: inizia con monolite, dividi solo quando hai un problema reale di scala"),
        ("API design REST",         "REST API design: risorse come URL, verbi HTTP corretti, status code precisi, versioning"),
        ("12-Factor App",           "12-Factor App: metodologia per app scalabili — config env, log su stdout, processi stateless"),
    ]),
    ("🔄 QUALITÀ DEL PROCESSO", [
        ("Code review",             "code review: revisione del codice da parte di un collega — trova bug, condividi conoscenza, alza la qualità"),
        ("Git workflow",            "git workflow professionale: feature branch, commit atomici, messaggi chiari, pull request"),
        ("Commit atomici",          "commit atomici: ogni commit fa una sola cosa logica — facile da revertire, facile da capire"),
        ("Documentazione",          "documentazione: docstring per ogni funzione pubblica, README chiaro, changelog — scrivi per il te futuro"),
        ("Logging professionale",   "logging Python: usa logging invece di print — livelli DEBUG INFO WARNING ERROR, formato strutturato"),
        ("Gestione errori robusta", "gestione errori robusta: non ignorare le eccezioni, logga il contesto, fallisci in modo prevedibile"),
        ("CI/CD concetti",          "CI/CD Continuous Integration Delivery: ogni push trigga test automatici — non si consegna codice non testato"),
        ("Code review checklist",   "code review checklist: leggibilità, test presenti, nessun magic number, nessun codice morto, sicurezza"),
        ("Technical debt",          "technical debt: il costo futuro di scorciatoie prese oggi — tienilo tracciato, riducilo gradualmente"),
    ]),
    ("🔒 SICUREZZA E PERFORMANCE", [
        ("OWASP Top 10",            "OWASP Top 10: i 10 rischi di sicurezza più comuni — injection, auth rotta, dati esposti, XSS, IDOR"),
        ("SQL Injection",           "SQL injection: mai costruire query con f-string — usa parametri bind o ORM sempre"),
        ("Input validation",        "validazione input: non fidarti mai dell'input esterno — valida tipo, formato, lunghezza, range"),
        ("Secrets management",      "gestione segreti: mai hardcodare password e API key nel codice — usa .env e variabili d'ambiente"),
        ("Principle of least privilege","principio del minimo privilegio: dai al codice solo i permessi strettamente necessari"),
        ("Caching strategico",      "caching strategico: memorizza risultati costosi — cache in memoria, Redis, invalidazione corretta"),
        ("Database N+1 problem",    "problema N+1 query database: una query per lista + una per ogni elemento — usa JOIN o prefetch"),
        ("Benchmarking",            "benchmarking: misura prima di ottimizzare — non ottimizzare per intuizione, usa dati reali"),
        ("Sicurezza delle dipendenze","sicurezza dipendenze: controlla vulnerabilità con pip audit, aggiorna regolarmente, usa lockfile"),
    ]),
    ("🎯 PENSIERO ENTERPRISE — Ragionare da pro", [
        ("Analisi prima del codice",   "analisi requisiti: scrivi i requisiti PRIMA di aprire l'editor — funzionali e non funzionali"),
        ("Trade-off consapevoli",      "trade-off: ogni scelta tecnica ha un costo — velocità vs memoria, semplicità vs flessibilità — documentali sempre"),
        ("Requisiti non funzionali",   "requisiti non funzionali: performance, scalabilità, sicurezza, manutenibilità — spesso più critici delle funzionalità"),
        ("Fail fast",                  "fail fast: meglio fallire subito con messaggio chiaro che continuare con dati corrotti — valida all'ingresso"),
        ("Defensive programming",      "programmazione difensiva: assumi che l'input sia sbagliato, i servizi siano giù, il codice abbia bug nascosti"),
        ("Design by Contract",         "design by contract: precondizioni, postcondizioni, invarianti — il contratto tra chi chiama e chi risponde"),
        ("Pensiero sistemico",         "pensiero sistemico: il tuo codice è parte di un sistema — conosci confini, dipendenze e impatti a cascata"),
        ("Decision log",               "decision log: documenta PERCHÉ hai scelto questa soluzione architetturale — il futuro te ti ringrazierà"),
        ("Strangler fig pattern",      "strangler fig: sostituisci un sistema legacy un pezzo alla volta — approccio graduale, niente big bang"),
        ("Premature optimization",     "prematura ottimizzazione: 'premature optimization is the root of all evil' — profila prima, ottimizza dopo"),
        ("Principio di Pareto",        "principio di Pareto: l'80% dei problemi di performance viene dal 20% del codice — trova e ottimizza quel 20%"),
        ("Pair programming",           "pair programming: due persone, un PC — driver scrive, navigator pensa — meno bug, più apprendimento"),
        ("Agile mindset",              "agile mindset: consegna spesso, piccoli incrementi, adattati ai cambiamenti — non pianificare tutto in anticipo"),
    ]),
    ("📐 SYSTEM DESIGN — Progettare su larga scala", [
        ("Back-of-envelope",           "stima approssimativa: calcola traffico, storage, banda PRIMA di progettare — 100M utenti × 1KB = 100GB"),
        ("Scalabilità",                "scalabilità orizzontale vs verticale: aggiungi macchine (horizontal) invece di potenziarne una sola (vertical)"),
        ("CAP Theorem",                "CAP Theorem: nei sistemi distribuiti puoi avere solo 2 di 3: Consistency, Availability, Partition tolerance"),
        ("Database: SQL vs NoSQL",     "SQL vs NoSQL: relazionale per dati strutturati con relazioni, NoSQL per flessibilità e scala orizzontale"),
        ("Caching livelli",            "caching a livelli: browser → CDN → reverse proxy → app server → database — ogni livello riduce la latenza"),
        ("Message queue",              "message queue: disaccoppia produttore e consumatore — gestisce picchi, garantisce ordine, permette retry"),
        ("Rate limiting",              "rate limiting: limita richieste per utente/IP — token bucket, leaky bucket, sliding window counter"),
        ("Circuit breaker",            "circuit breaker: se un servizio fallisce troppo, smetti di chiamarlo — stato: closed → open → half-open"),
        ("Idempotenza",                "idempotenza: operazione ripetuta N volte = risultato uguale a 1 volta — cruciale per retry e API REST"),
        ("Load balancing",             "load balancing: distribuisci il carico tra più server — round robin, least connections, weighted"),
        ("Database sharding",          "database sharding: dividi il DB in frammenti — ogni shard ha un sottoinsieme dei dati per scalare"),
        ("Event sourcing",             "event sourcing: salva gli eventi invece dello stato finale — puoi ricostruire qualsiasi stato passato"),
    ]),
    ("💎 ALGORITMI ENTERPRISE — Livello avanzato", [
        ("Heap / Priority Queue",      "heap Python: heapq module, min-heap, coda con priorità — trova i K elementi maggiori in O(n log k)"),
        ("Trie (Prefix Tree)",         "trie: struttura ad albero per stringhe — autocomplete, dizionari, ricerca prefisso in O(len parola)"),
        ("Dijkstra shortest path",     "Dijkstra: percorso più breve in grafo pesato con pesi positivi — usato in GPS, reti — O((V+E) log V)"),
        ("Union-Find (DSU)",           "Union-Find Disjoint Set: componenti connesse, rilevamento cicli — O(α(n)) quasi costante"),
        ("LRU Cache",                  "LRU Cache O(1): Least Recently Used con OrderedDict — get e put in O(1) — chiesto in ogni colloquio FAANG"),
        ("Sliding Window",             "sliding window: subarray con condizione — trasforma O(n²) in O(n) — massima somma K elementi contigui"),
        ("Two Pointers",               "two pointers: due indici che si avvicinano — coppia con somma target, palindromo, contenitore d'acqua"),
        ("Segment Tree",               "segment tree: query su intervalli (min, max, somma) in O(log n) — update O(log n) — usato in competitive"),
        ("Bloom Filter",               "bloom filter: struttura probabilistica — 'forse presente' o 'sicuramente assente' — spazio O(m) vs O(n)"),
        ("Consistent Hashing",         "consistent hashing: distribuisci chiavi su nodi minimizzando ridistribuzione — usato in sistemi distribuiti"),
        ("Backtracking",               "backtracking: prova tutte le soluzioni possibili, torna indietro se fallisce — N-Regine, Sudoku, permutazioni"),
        ("Memoization vs Tabulation",  "memoization (top-down, ricorsiva) vs tabulation (bottom-up, iterativa) — due modi di fare programmazione dinamica"),
    ]),
    ("🧩 PROGRAMMAZIONE DINAMICA — DP completa", [
        ("Zaino 0/1",                  "zaino 0/1 knapsack: ogni oggetto si prende intero o si lascia — dp[i][w] = max valore con i oggetti e capacità w"),
        ("Coin Change",                "coin change: minimo numero di monete per un importo — dp[i] = min(dp[i-moneta]+1) per ogni moneta ≤ i"),
        ("LCS",                        "LCS Longest Common Subsequence: sottosequenza comune più lunga — dp[i][j] da confronto s1[i] e s2[j]"),
        ("Edit Distance",              "edit distance Levenshtein: minimo operazioni (insert/delete/replace) per trasformare stringa A in B — spell check"),
        ("LIS",                        "LIS Longest Increasing Subsequence: sottosequenza strettamente crescente più lunga — dp[i]=1+max(dp[j]) j<i"),
        ("Matrix Chain",               "matrix chain multiplication: ordine ottimale per moltiplicare matrici — minimizza il numero di operazioni scalari"),
        ("Egg Drop",                   "egg drop problem: minimo numero di tentativi per trovare il piano critico con K uova e N piani — dp[k][n]"),
        ("Rod Cutting",                "rod cutting: taglia una barra in pezzi per massimizzare il ricavo — dp[i] = max(prezzo[j] + dp[i-j])"),
    ]),
    ("🔤 ALGORITMI SU STRINGHE", [
        ("KMP Search",                 "KMP Knuth-Morris-Pratt: ricerca pattern in O(n+m) con failure function — evita di ricominciare da zero"),
        ("Rabin-Karp",                 "Rabin-Karp: ricerca con rolling hash — confronta hash del pattern con hash di ogni finestra del testo"),
        ("Z-Algorithm",                "Z-algorithm: Z[i] = prefisso più lungo = sottostringa da i — concatena pattern+'$'+testo, trova Z[i]=len(pattern)"),
        ("Boyer-Moore",                "Boyer-Moore: ricerca pattern con salti — buona regola del carattere e buona regola del suffisso — O(n/m) best case"),
        ("Suffix Array",               "suffix array: array di tutti i suffissi ordinati — ricerca pattern in O(m log n) — base per molti algoritmi su stringhe"),
        ("Aho-Corasick",               "Aho-Corasick: ricerca di MULTIPLI pattern simultaneamente in O(n+m+z) — trie + failure links — usato in antivirus"),
        ("Manacher",                   "algoritmo di Manacher: trova tutte le sottostringhe palindrome in O(n) — più efficiente dell'approccio naive O(n²)"),
    ]),
    ("🌐 GRAFI AVANZATI — Teoria dei grafi", [
        ("Bellman-Ford",               "Bellman-Ford: percorso minimo anche con pesi negativi — rilassa tutti gli archi V-1 volte — O(V×E)"),
        ("Floyd-Warshall",             "Floyd-Warshall: tutti i percorsi minimi tra tutte le coppie — dp[i][j] con intermediario k — O(V³)"),
        ("Kruskal MST",                "Kruskal: Minimum Spanning Tree — ordina archi per peso, aggiungili se non creano ciclo (Union-Find) — O(E log E)"),
        ("Prim MST",                   "Prim: MST con coda a priorità — espandi il nodo più economico dal MST corrente — O((V+E) log V)"),
        ("A* Search",                  "A*: ricerca con euristica — f(n)=g(n)+h(n) — più veloce di Dijkstra con buona euristica — GPS, videogiochi"),
        ("Topological Sort",           "topological sort: ordine lineare di un DAG — Kahn (BFS con in-degree) o DFS con stack — dipendenze software"),
        ("Componenti Fortemente Connesse","SCC Strongly Connected Components: Tarjan o Kosaraju — sottografi dove ogni nodo raggiunge ogni altro"),
        ("Flusso Massimo",             "max flow Ford-Fulkerson: massimo flusso da sorgente a pozzo in un grafo capacitato — matching bipartito"),
    ]),
    ("💛 GREEDY — Algoritmi Golosi", [
        ("Activity Selection",         "activity selection: massimo numero di attività non sovrapposte — ordina per fine, scegli sempre la prima disponibile"),
        ("Huffman Coding",             "Huffman coding: compressione ottimale — frequenze → albero binario (unisci i 2 meno frequenti) — ZIP, PNG"),
        ("Zaino Frazionario",          "zaino frazionario: puoi spezzare gli oggetti — ordina per densità valore/peso, prendi i migliori prima — O(n log n)"),
        ("Job Scheduling",             "job scheduling con deadline: massimizza il profitto — ordina per profitto decrescente, assegna al massimo slot disponibile"),
        ("Algoritmo di Dijkstra",      "Dijkstra come greedy: scegli sempre il nodo non visitato con distanza minima — greedy ottimale su grafi non negativi"),
        ("Moneta greedy",              "problema moneta greedy: per certi sistemi monetari (es. europeo), greedy è ottimale — non sempre! Usa DP se necessario"),
    ]),
    ("🔁 BACKTRACKING — Ricerca Esaustiva", [
        ("N-Queens",                   "N regine su scacchiera N×N: backtracking — prova colonna per colonna, torna indietro se nessuna colonna funziona"),
        ("Sudoku Solver",              "sudoku con backtracking: per ogni cella vuota prova 1-9 con verifica riga/colonna/box — torna indietro se impossibile"),
        ("Permutazioni",               "permutazioni con backtracking: genera tutte le N! permutazioni — ricorsione + swap + backtrack — O(N! × N)"),
        ("Subset Sum",                 "subset sum: esistono elementi che sommano a target? — backtracking o DP — variante: conta tutti i subset"),
        ("Colorazione Grafi",          "graph coloring: assegna colori ai nodi tale che adiacenti abbiano colori diversi — NP-completo in generale"),
        ("Hamiltonian Path",           "cammino hamiltoniano: attraversa ogni nodo esattamente una volta — NP-completo — backtracking con pruning"),
    ]),
    ("🔢 ALGORITMI MATEMATICI", [
        ("GCD — Euclide",              "GCD algoritmo di Euclide: MCD(a,b)=MCD(b,a%b) — O(log min(a,b)) — base di crittografia RSA e frazioni"),
        ("Extended GCD",               "GCD esteso: trova x,y tale che ax+by=MCD(a,b) — usato in RSA per trovare l'inverso modulare"),
        ("Potenza Modulare",           "fast exponentiation: b^e mod m in O(log e) — fondamentale in RSA — b^e=(b^(e/2))² se e pari"),
        ("Miller-Rabin",               "Miller-Rabin: test probabilistico di primalità in O(k log²n) — usato per generare chiavi RSA da 512-4096 bit"),
        ("Karatsuba",                  "Karatsuba: moltiplicazione divide-et-impera in O(n^1.585) — solo 3 moltiplicazioni ricorsive invece di 4"),
        ("Crivo di Eratostene",        "crivo di Eratostene: trova tutti i primi ≤ n in O(n log log n) — segna i multipli di ogni primo trovato"),
        ("Trasformata di Fourier",     "FFT Fast Fourier Transform: converte segnale tempo→frequenza in O(n log n) — audio, immagini, moltiplicazione polinomi"),
    ]),
    ("🏗️ STRUTTURE DATI AVANZATE — Livello esperto", [
        ("AVL Tree",                   "AVL tree: BST auto-bilanciato con rotazioni — mantiene |h(sx)-h(dx)|≤1 — ricerca/insert/delete O(log n) garantiti"),
        ("Red-Black Tree",             "red-black tree: BST bilanciato con 5 proprietà colore — più veloce di AVL in scrittura — usato in std::map C++"),
        ("B-Tree",                     "B-tree: albero bilanciato con nodi che contengono più chiavi — minimizza accessi disco — usato in database e filesystem"),
        ("Segment Tree",               "segment tree: query range (somma/min/max) in O(log n) — update O(log n) — più flessibile del Fenwick Tree"),
        ("Fenwick Tree BIT",           "Fenwick Tree Binary Indexed Tree: prefix sum aggiornabili in O(log n) — usa bit meno significativo (i & -i)"),
        ("Skip List",                  "skip list: lista con livelli multipli per ricerca in O(log n) medio — alternativa probabilistica ad AVL Tree"),
        ("Suffix Array",               "suffix array + LCP array: struttura per ricerca di pattern, LCS, occorrenze — O(n log n) costruzione"),
    ]),
    ("🔒 SICUREZZA INFORMATICA ENTERPRISE", [
        ("OWASP Top 10",               "OWASP Top 10: le 10 vulnerabilità più critiche — injection, broken auth, XSS, IDOR, SSRF, XXE, dati esposti, logging assente"),
        ("SQL Injection",              "SQL injection: WHERE 1=1 bypass auth — parameterized query come difesa — blind SQLi, time-based, error-based, second-order"),
        ("XSS Cross-Site Scripting",   "XSS: script malevolo iniettato in pagina — reflected (URL), stored (DB), DOM-based — difesa: CSP header, escape output, DOMPurify"),
        ("CSRF",                       "CSRF Cross-Site Request Forgery: azione non autorizzata per conto dell'utente — difesa: CSRF token, SameSite=Strict cookie, origin header check"),
        ("Crittografia simmetrica",    "AES Advanced Encryption Standard: stessa chiave per cifrare e decifrare — blocchi 128 bit, chiavi 128/192/256 bit — modalità CBC, GCM (autenticata)"),
        ("Crittografia asimmetrica",   "RSA: chiave pubblica cifra, chiave privata decifra — basato su fattorizzazione di grandi numeri — 2048/4096 bit — firma digitale, certificati X.509"),
        ("Hashing e Salt",             "bcrypt/argon2: hash lento e salato per password — salt = stringa casuale aggiunta prima dell'hash — rainbow table inutili — cost factor regolabile"),
        ("Penetration Testing",        "pentest workflow: reconnaissance → scanning (nmap) → exploitation → post-exploitation → reporting — scope, regole d'ingaggio, CVSS scoring"),
        ("Zero Trust",                 "Zero Trust Architecture: 'non fidarti mai, verifica sempre' — ogni richiesta autenticata e autorizzata — micro-segmentazione, least privilege, MFA"),
        ("SIEM e Log Analysis",        "SIEM Security Information Event Management: aggrega log da tutti i sistemi — correlazione eventi — alert su anomalie — risposta incidenti SOC"),
        ("CTF Capture The Flag",       "CTF: competizione sicurezza — categorie: web, crypto, pwn (binary exploit), reversing, forensics — strumenti: pwntools, ghidra, burp suite, wireshark"),
        ("Vulnerability Management",   "gestione vulnerabilità: CVE, CVSS score (0-10), NVD database — patch management, responsible disclosure, bug bounty, triaging per priorità"),
    ]),
    ("🐧 LINUX ENTERPRISE — Amministrazione avanzata", [
        ("Filesystem Hierarchy FHS",   "FHS Linux: /bin eseguibili, /etc config, /var dati variabili, /proc kernel virtuale, /sys hardware virtuale, /home utenti, /opt software opzionale"),
        ("Permessi e ACL",             "chmod 755 = rwxr-xr-x — setuid (esegui come owner), setgid, sticky bit (/tmp) — ACL con setfacl/getfacl: permessi granulari per utenti specifici"),
        ("Processi e Segnali",         "ps aux, top, htop — PID, PPID, stato R/S/Z/D — kill -15 SIGTERM (graceful), kill -9 SIGKILL (forza) — nice/renice priorità — /proc/PID/"),
        ("Systemd e servizi",          "systemctl start/stop/enable/disable/status — journalctl -u servizio -f — unit file in /etc/systemd/system/ — socket activation, timer, targets"),
        ("Networking Linux",           "ip addr show, ip route, ss -tlnp — tcpdump -i eth0 port 80 — configurazione /etc/netplan/ — NetworkManager — bridge, bond, vlan — ethtool"),
        ("Bash scripting avanzato",    "bash: array ${arr[@]}, funzioni, getopts — subshell $(cmd), process substitution <(cmd) — trap per segnali — set -euo pipefail — heredoc <<EOF"),
        ("Cron e Scheduling",          "crontab -e: m h dom mon dow comando — /etc/cron.d/, /etc/cron.daily/ — anacron per macchine non H24 — systemd timer come alternativa moderna"),
        ("LVM Logical Volume Manager", "LVM: PV (disco fisico) → VG (gruppo volumi) → LV (volume logico) — resize online senza downtime, snapshot, thin provisioning — pvs vgs lvs"),
        ("SSH hardening",              "sshd_config: PermitRootLogin no, PasswordAuthentication no, AllowUsers — fail2ban blocca bruteforce — chiave ed25519 — port knocking — 2FA"),
        ("iptables e nftables",        "iptables: catene INPUT/OUTPUT/FORWARD, tabelle filter/nat/mangle — regole stateful con conntrack — nftables sintassi moderna — ufw come frontend"),
        ("Docker e container",         "docker run/build/push/compose — Dockerfile: FROM, RUN, COPY, ENTRYPOINT, HEALTHCHECK — namespace PID/net/mount, cgroup risorse — rootless Docker"),
        ("Ansible automazione",        "Ansible: playbook YAML, inventory, roles, handlers, variables — idempotente — agentless via SSH — vault per segreti — galaxy per roles condivisi"),
        ("Performance e tuning",       "sysctl vm.swappiness, net.core.somaxconn — ulimit, /etc/security/limits.conf — vmstat, iostat, sar — perf top, strace, ltrace — huge pages, NUMA"),
    ]),
    ("📐 GEOMETRIA COMPUTAZIONALE", [
        ("Convex Hull",                "convex hull involucro convesso: Graham Scan in O(n log n) — elastico attorno ai chiodi — computer graphics, GIS"),
        ("Line Intersection",          "intersezione di segmenti: algoritmo di Shamos-Hoey in O(n log n) — sweep line — computational geometry base"),
        ("Closest Pair of Points",     "coppia di punti più vicini: divide-et-impera in O(n log n) — divide, risolvi, combina con striscia centrale"),
        ("Point in Polygon",           "punto dentro poligono: ray casting — conta quante volte il raggio interseca i lati — O(n) — GIS, collision"),
    ]),
    ("🌐 PROTOCOLLI DI RETE — Come parlano le macchine", [
        ("Modello OSI",                "modello OSI a 7 strati: fisico, datalink, rete, trasporto, sessione, presentazione, applicazione — ogni strato ha un compito preciso"),
        ("TCP vs UDP",                 "TCP (affidabile, ordinato, controllo errori) vs UDP (veloce, senza garanzie) — scegli TCP per dati, UDP per streaming live"),
        ("IP e Subnetting",            "IP address: 192.168.1.10 — 4 ottetti, notazione CIDR /24 = 256 host, subnet mask, broadcast, host range"),
        ("HTTP e HTTPS",               "HTTP verbi: GET (leggi), POST (crea), PUT (aggiorna tutto), PATCH (aggiorna parte), DELETE — status code: 200 OK, 404 Not Found, 500 Server Error"),
        ("DNS — Domain Name System",   "DNS risolve nomi in indirizzi IP — query ricorsiva: browser → resolver → root → TLD → authoritative — cache TTL"),
        ("TLS e SSL",                  "TLS handshake: client hello → server certificate → chiave pubblica → session key simmetrica — HTTPS è HTTP dentro un tunnel TLS"),
        ("WebSocket",                  "WebSocket: connessione full-duplex persistente su TCP — upgrade da HTTP — ideale per chat, giochi online, notifiche in tempo reale"),
        ("REST API",                   "REST: risorse come URL (/utenti/42), verbi HTTP corretti, stateless, JSON come formato — non REST se lo stato è nel server"),
        ("gRPC e Protocol Buffers",    "gRPC: RPC ad alte prestazioni su HTTP/2 — Protocol Buffers (protobuf): schema binario tipizzato, 10× più compatto di JSON"),
        ("OAuth2 e JWT",               "OAuth2: delega autorizzazione senza condividere password — access token (breve vita) + refresh token — JWT: header.payload.signature in base64"),
        ("SSH — Secure Shell",         "SSH: connessione remota cifrata — autenticazione con chiave pubblica/privata RSA/Ed25519 — port forwarding, tunneling, SCP per trasferire file"),
        ("SMTP IMAP POP3",             "SMTP invia email (porta 587) — IMAP legge da server mantenendo sincronizzazione — POP3 scarica e cancella dal server — tutti su TLS"),
    ]),
    ("📐 MATEMATICA BASE — Fondamenta per capire tutto il resto", [
        ("Algebra ed equazioni",       "algebra: equazione ax+b=0 → x=-b/a, sistemi lineari 2×2, disequazioni — la matematica come linguaggio per descrivere relazioni"),
        ("Funzioni",                   "funzione f(x): ogni x dà un solo y — dominio (x validi), codominio (y possibili), grafico — composizione f(g(x)), funzione inversa"),
        ("Geometria euclidea",         "geometria: angoli (gradi/radianti), area triangolo=base×altezza/2, teorema di Pitagora a²+b²=c², cerchio area=πr², circonferenza=2πr"),
        ("Trigonometria",              "sin, cos, tan sulla circonferenza unitaria — sin²+cos²=1 — sin(α+β), angoli notevoli 30°/45°/60° — usata in grafica, fisica, segnali"),
        ("Logaritmi ed esponenziali",  "e^x e ln(x) sono inversi — log(a×b)=log(a)+log(b) — crescita esponenziale vs logaritmica — base del calcolo della complessità O(log n)"),
        ("Numeri complessi",           "numero complesso z=a+bi dove i²=-1 — modulo |z|=√(a²+b²), argomento φ=arctan(b/a) — forma polare z=r·e^(iφ) — formula di Eulero e^(iπ)=-1"),
        ("Combinatoria",               "permutazioni P(n,k)=n!/(n-k)!, combinazioni C(n,k)=n!/(k!(n-k)!) — binomio di Newton (a+b)^n — usato in probabilità e algoritmi"),
    ]),
    ("📈 CALCOLO — Analisi matematica dal limite all'integrale", [
        ("Limiti e continuità",        "limite: lim(x→a) f(x) = L — il valore a cui f si avvicina — forme indeterminate 0/0 e ∞/∞ — continuità: il grafico non si spezza mai"),
        ("Derivata — cos'è",           "derivata f'(x) = pendenza della tangente nel punto x — velocità istantanea — f'(x) = lim(h→0) [f(x+h)-f(x)]/h"),
        ("Regole di derivazione",      "derivata di x^n = nx^(n-1), sin→cos, cos→-sin, e^x→e^x, ln(x)→1/x — regola della catena: [f(g(x))]' = f'(g(x))·g'(x)"),
        ("Massimi minimi e studio",    "massimo/minimo dove f'(x)=0 — f''>0 minimo, f''<0 massimo — studio funzione: dominio, segno, derivata, grafico completo"),
        ("Integrale indefinito",       "integrale ∫f(x)dx = antiderivata F(x)+C — integrazione per sostituzione e per parti — inverso della derivata"),
        ("Integrale definito",         "∫(a,b)f(x)dx = area algebrica tra f e asse x — Teorema Fondamentale del Calcolo: F(b)-F(a) — somme di Riemann come approssimazione"),
        ("Serie di Taylor",            "approssima qualsiasi funzione con polinomio infinito: f(x)=f(a)+f'(a)(x-a)+f''(a)(x-a)²/2!+... — sin(x)≈x-x³/6 per x piccoli"),
        ("Equazioni differenziali ODE","ODE: equazione con f e le sue derivate — separazione variabili: dy/dx=f(x)g(y) → ∫dy/g(y)=∫f(x)dx — modella crescita, oscillazioni, circuiti"),
    ]),
    ("🔬 MATEMATICA AVANZATA — Algebra lineare, probabilità e trasformate", [
        ("Vettori",                    "vettore: freccia con direzione e modulo — somma, scalare, prodotto scalare a·b=|a||b|cos(θ) — prodotto vettoriale, ortogonalità"),
        ("Matrici e sistemi lineari",  "matrice: tabella di numeri — moltiplicazione (A×B)ij=riga i × colonna j — eliminazione di Gauss, determinante, inversa — Ax=b"),
        ("Autovalori e autovettori",   "Av=λv — il vettore v non cambia direzione sotto A, scala solo di λ — diagonalizzazione, PCA in machine learning, PageRank di Google"),
        ("Calcolo multivariabile",     "funzioni f(x,y,...): derivata parziale ∂f/∂x (y costante) — gradiente ∇f = vettore della massima salita — ottimizzazione ML"),
        ("Probabilità",                "P(A)∈[0,1], P(A∪B)=P(A)+P(B)-P(A∩B) — variabile aleatoria, valore atteso E[X], varianza Var(X) — distribuzione normale (campana)"),
        ("Statistica",                 "media, mediana, moda, deviazione standard — correlazione di Pearson — regressione lineare — test di ipotesi, p-value, intervallo di confidenza"),
        ("Trasformata di Fourier",     "FFT: decompone qualsiasi segnale in somma di sinusoidi — F(ω)=∫f(t)e^(-iωt)dt — applicata in audio, immagini, compressione JPEG, ML"),
        ("Trasformata di Laplace",     "L{f(t)}=F(s)=∫f(t)e^(-st)dt — trasforma ODE in equazioni algebriche in s — funzione di trasferimento, analisi di stabilità, controllo automatico"),
    ]),
]

# Lista piatta per accesso per indice (compatibilità con il menu)
ARGOMENTI = [(nome, desc) for _, sezione in SEZIONI_ARGOMENTI for nome, desc in sezione]

# ── Sezioni raggruppate per menu ──────────────────────────────────────────────

_TITOLI_MATEMATICA = {
    "📐 MATEMATICA BASE — Fondamenta per capire tutto il resto",
    "📈 CALCOLO — Analisi matematica dal limite all'integrale",
    "🔬 MATEMATICA AVANZATA — Algebra lineare, probabilità e trasformate",
}
_TITOLI_SICUREZZA = {
    "🔒 SICUREZZA INFORMATICA ENTERPRISE",
    "🐧 LINUX ENTERPRISE — Amministrazione avanzata",
    "🌐 PROTOCOLLI DI RETE — Come parlano le macchine",
}

# ── Sezioni matematica aggiuntive (non in SEZIONI_ARGOMENTI) ──────────────────

SEZIONI_MATEMATICA_EXTRA = [
    ("🔢 ARITMETICA E TEORIA DEI NUMERI", [
        ("Numeri N Z Q R C",           "insiemi numerici: naturali, interi, razionali, reali, complessi — assiomi di Peano, densità di Q in R, cardinalità infinita"),
        ("Divisibilità e MCD",         "divisibilità: a|b, MCD algoritmo di Euclide, mcm=a*b/MCD — teorema fondamentale dell'aritmetica: ogni intero>1 prodotto unico di primi"),
        ("Numeri primi",               "numeri primi: infinità dei primi (dimostrazione di Euclide), crivello di Eratostene, teorema dei numeri primi π(x)≈x/ln(x)"),
        ("Aritmetica modulare",        "congruenza a≡b (mod n) — classi di equivalenza Z/nZ — operazioni in Z_n — invertibile se e solo se MCD(a,n)=1"),
        ("Teorema di Fermat-Eulero",   "piccolo teorema di Fermat: a^p≡a (mod p) — funzione di Eulero φ(n) — Eulero: a^φ(n)≡1 (mod n) se MCD(a,n)=1"),
        ("Teorema cinese del resto",   "sistema x≡a₁(mod m₁), x≡a₂(mod m₂) — soluzione unica mod m₁m₂ se MCD(m₁,m₂)=1 — applicazioni in crittografia e informatica"),
        ("Equazioni diofantine",       "equazione ax+by=c — soluzioni intere esistono ↔ MCD(a,b)|c — teorema di Bezout: ax+by=MCD(a,b) — parametrizzazione soluzioni"),
        ("Ricorrenze e Fibonacci",     "Fibonacci Fn=Fn-1+Fn-2, formula di Binet Fn=(φⁿ-ψⁿ)/√5, rapporto aureo φ=(1+√5)/2 — ricorrenze lineari: soluzione omogenea+particolare"),
        ("RSA — teoria dei numeri",    "RSA: scegli p,q primi → n=pq, φ(n)=(p-1)(q-1) → e coprimo con φ(n), d=e⁻¹ mod φ(n) — cifra con eˢ, decifra con dˢ — basato su fattorizzazione"),
    ]),
    ("📊 GEOMETRIA ANALITICA", [
        ("Retta nel piano",            "retta: y=mx+q esplicita, ax+by+c=0 implicita — pendenza m=tanα, intercetta — distanza punto-retta d=|ax₀+by₀+c|/√(a²+b²)"),
        ("Parabola",                   "parabola y=ax²+bx+c: vertice V=(-b/2a, f(-b/2a)) — fuoco e direttrice — asse di simmetria x=-b/2a — delta discriminante"),
        ("Ellisse",                    "ellisse x²/a²+y²/b²=1: semiassi a>b>0, fuochi (±c,0) con c²=a²-b², eccentricità e=c/a∈(0,1) — cerchio caso speciale a=b"),
        ("Iperbole",                   "iperbole x²/a²-y²/b²=1: fuochi (±c,0) con c²=a²+b², asintoti y=±(b/a)x, eccentricità e>1 — iperbole rettangolare xy=k"),
        ("Coordinate polari",          "coordinate polari (r,θ): x=r·cosθ, y=r·sinθ — conversione cartesiane↔polari — curve polari: spirale r=aθ, cardioide r=a(1+cosθ)"),
        ("Geometria 3D",               "retta 3D parametrica r(t)=P₀+t·v — piano ax+by+cz+d=0, normale n=(a,b,c) — distanza punto-piano |ax₀+by₀+cz₀+d|/√(a²+b²+c²)"),
        ("Trasformazioni geometriche", "traslazione T(tx,ty), rotazione di θ con matrice [[cosθ,-sinθ],[sinθ,cosθ]], riflessione, scalatura — composizione = prodotto matrici"),
    ]),
    ("🔄 TRIGONOMETRIA AVANZATA", [
        ("Formule di addizione",       "sin(α±β)=sinα·cosβ±cosα·sinβ — cos(α±β)=cosα·cosβ∓sinα·sinβ — tan(α+β)=(tanα+tanβ)/(1-tanα·tanβ) — duplicazione e bisezione"),
        ("Equazioni trigonometriche",  "sin(x)=k → x=arcsin(k)+2kπ o x=π-arcsin(k)+2kπ — cos(x)=k, tan(x)=k — equazioni generali e particolari — periodo"),
        ("Funzioni inverse trig",      "arcsin: [-1,1]→[-π/2,π/2], arccos: [-1,1]→[0,π], arctan: R→(-π/2,π/2) — identità: arcsin+arccos=π/2, derivate 1/√(1-x²)"),
        ("Prodotto scalare e angoli",  "prodotto scalare a·b=|a||b|cosθ — angolo tra vettori — proiezione — distanza angolare — applicazioni in computer graphics e ML"),
        ("Identità fondamentali",      "sin²+cos²=1, 1+tan²=sec², 1+cot²=csc² — formule prostaferesi: prodotto→somma — integrali trigonometrici con identità"),
    ]),
    ("📉 SUCCESSIONI E SERIE", [
        ("Successioni",                "successione {aₙ}: limite lim(n→∞)aₙ=L — criteri: monotona limitata converge, Cauchy ↔ converge in R — sottosuccessioni"),
        ("Confronto e squeeze",        "squeeze theorem: aₙ≤bₙ≤cₙ e aₙ→L, cₙ→L ⟹ bₙ→L — confronto: aₙ≤bₙ e aₙ→+∞ ⟹ bₙ→+∞ — applicazioni classiche"),
        ("Serie numeriche",            "serie Σaₙ: somme parziali Sₙ — geometrica Σrⁿ=1/(1-r) per |r|<1 — armonica Σ1/n=+∞ — telescopica — serie di Leibniz"),
        ("Test di convergenza",        "test rapporto D'Alembert: lim|aₙ₊₁/aₙ|<1 conv, >1 div — test radice Cauchy — test integrale — Leibniz per alternanti — Abel-Dirichlet"),
        ("Serie di potenze",           "Σcₙ(x-a)ⁿ: raggio convergenza R=1/limsup|cₙ|^(1/n) — dentro (-R,R) converge assolutamente — derivazione e integrazione termine a termine"),
        ("Serie di Fourier",           "f(x)=a₀/2+Σ(aₙcos(nπx/L)+bₙsin(nπx/L)) — coefficienti aₙ=(1/L)∫f·cos, bₙ=(1/L)∫f·sin — convergenza, fenomeno di Gibbs"),
        ("Trasformata Z",              "F(z)=Σf[n]z⁻ⁿ — analoga discreta di Laplace — regione di convergenza — usata in filtri digitali IIR/FIR, controllo discreto"),
    ]),
    ("🌍 CALCOLO MULTIVARIABILE", [
        ("Funzioni di più variabili",  "f:Rⁿ→R — dominio, curve/superfici di livello, limite — continuità in Rⁿ — punto di sella vs estremo — grafico di f(x,y) in 3D"),
        ("Derivate parziali",          "∂f/∂x: derivata rispetto a x con y costante — regola della catena ∂f/∂t=∂f/∂x·∂x/∂t+∂f/∂y·∂y/∂t — derivate miste: teorema di Schwarz"),
        ("Gradiente e direzione",      "∇f=(∂f/∂x,∂f/∂y,...) — derivata direzionale D_v f=∇f·v̂ — ∇f punta alla massima salita — curva di livello perpendicolare a ∇f"),
        ("Hessiana e ottimizzazione",  "Hessiana H=[∂²f/∂xᵢ∂xⱼ] — punto critico ∇f=0 — det(H)>0 e H₁₁>0: minimo, H₁₁<0: massimo, det(H)<0: sella"),
        ("Moltiplicatori di Lagrange", "ottimizza f(x,y) con vincolo g(x,y)=c: ∇f=λ∇g — fondamentale in economia, ML, fisica — estensione a più vincoli"),
        ("Integrali multipli",         "integrale doppio ∬f dA — teorema di Fubini — cambio variabili (Jacobiano) — coordinate polari, cilindriche, sferiche — integrale triplo"),
        ("Integrali di linea",         "∫_C f·dr — lavoro campo vettoriale — teorema fondamentale per campi conservativi — indipendenza dal cammino — potenziale"),
        ("Teoremi integrali",          "teorema di Green (piano), Stokes (superfici), Divergenza/Gauss (volumi) — unificano le forme: ∫∫∫div F dV = ∯F·dS"),
    ]),
    ("🌊 EQUAZIONI DIFFERENZIALI ODE", [
        ("ODE 1° ordine separabili",   "y'=f(x)g(y) → ∫dy/g(y)=∫f(x)dx — lineari y'+p(x)y=q(x), fattore integrante μ=e^∫p — esatte M dx+N dy=0 con ∂M/∂y=∂N/∂x"),
        ("ODE lineare 2° ordine",      "ay''+by'+cy=0 — equazione caratteristica ar²+br+c=0 — 3 casi: due reali y=c₁e^r₁x+c₂e^r₂x, doppia, complesse coniugate e^αx(cos/sin)"),
        ("Metodo variazione costanti", "ODE non omogenea: y=yₒ+y_p — variazione costanti: supponi c₁(x),c₂(x) — sistema 2 equazioni — annichilatori e metodo dei coefficienti indeterminati"),
        ("Sistemi di ODE",             "x'=Ax — autovalori/autovettori di A — soluzione e^λt·v — nodi (λ reali), fuochi (λ complessi), centri (λ immaginari), selle — ritratto di fase"),
        ("Laplace per ODE",            "L{y'}=sY-y(0), L{y''}=s²Y-sy(0)-y'(0) — trasforma ODE → equazione algebrica — condizioni iniziali incluse — funzione di trasferimento"),
        ("Serie di potenze per ODE",   "y=Σaₙxⁿ, sostituisci e trova ricorrenza per aₙ — metodo di Frobenius per punti singolari — equazione di Bessel, di Legendre"),
        ("Stabilità e dinamica",       "equilibrio y*: stabile se |y(t)-y*|→0, instabile altrimenti — linearizzazione locale — ciclo limite (Hopf) — biforcazioni saddle-node, pitch"),
    ]),
    ("🌐 PDE — Equazioni Differenziali alle Derivate Parziali", [
        ("Classificazione PDE",        "PDE: Au_xx+Bu_xy+Cu_yy+... — discriminante B²-4AC: <0 ellittica (Laplace), =0 parabolica (calore), >0 iperbolica (onde) — ordine e linearità"),
        ("Equazione del calore",       "∂u/∂t=α∇²u — separazione variabili u=X(x)T(t) → X''/X=T'/(αT)=-λ — autofunzioni sin/cos — soluzione come serie di Fourier"),
        ("Equazione delle onde",       "∂²u/∂t²=c²∂²u/∂x² — D'Alembert: u(x,t)=f(x-ct)+g(x+ct) — corda vibrante — onde stazionarie — riflessione alle estremità"),
        ("Equazione di Laplace",       "∇²u=0 — funzioni armoniche (media sulla sfera = valore al centro) — problema di Dirichlet — separazione in polari: serie di Fourier radiale"),
        ("Separazione delle variabili","u(x,t)=X(x)T(t) — riduce PDE a ODE — Sturm-Liouville: -[p(x)y']'+q(x)y=λw(x)y — autovalori reali, autofunzioni ortogonali"),
        ("Metodi numerici per PDE",    "differenze finite: ∂u/∂t≈(u^(n+1)-uⁿ)/Δt — griglia spaziale Δx — schema esplicito (CFL: Δt≤Δx²/2α) — schema implicito incondizionatamente stabile"),
    ]),
    ("🔮 ANALISI COMPLESSA", [
        ("Funzioni di var. complessa",  "f:C→C, z=x+iy, f(z)=u(x,y)+iv(x,y) — limite e continuità nel piano complesso — funzioni polinomiali, razionali"),
        ("Funzioni olomorfe",          "differenziabilità complessa: f'(z)=lim[f(z+h)-f(z)]/h — condizioni Cauchy-Riemann: ∂u/∂x=∂v/∂y e ∂u/∂y=-∂v/∂x — funzione armonica"),
        ("Funzioni elementari C",      "eˢ=eˣ(cosy+isiny) — sin z=(e^iz-e^-iz)/(2i) — log z=ln|z|+i·arg(z) (multivalore) — ramo principale — formula di Eulero e^(iπ)=-1"),
        ("Teorema integrale Cauchy",   "∮_C f(z)dz=0 se f olomorfa in dominio s.c. — deformazione del cammino — teorema Cauchy-Goursat — formula integrale f(z₀)=1/(2πi)∮f/(z-z₀)"),
        ("Serie di Laurent",           "f(z)=Σcₙ(z-z₀)ⁿ per n da -∞ a +∞ — parte principale (n<0): singolarità rimovibile (finita), polo (finita), essenziale (infinita)"),
        ("Teorema dei residui",        "∮f dz=2πi·Σ(residui interni) — res(f,z₀)=c₋₁ — calcolo: lim(z-z₀)f(z) per polo semplice — integrazione di funzioni reali difficili"),
        ("Trasformazioni conformi",    "f olomorfa con f'≠0 conserva angoli — applicazioni: fluidodinamica, elettromagnetismo — trasformazione di Möbius w=(az+b)/(cz+d)"),
    ]),
    ("📏 GEOMETRIA DIFFERENZIALE", [
        ("Curve nel piano",            "parametrizzazione r(t)=(x(t),y(t)) — vettore tangente r'(t)/|r'(t)| — lunghezza arco L=∫|r'(t)|dt — riparametrizzazione per arco"),
        ("Curvatura e torsione",       "curvatura κ=|r'×r''|/|r'|³ — cerchio κ=1/R, retta κ=0 — cerchio osculatore — torsione τ misura quanto la curva esce dal piano osculatore"),
        ("Terna di Frenet",            "T=r'/|r'| tangente, N=T'/|T'| normale principale, B=T×N binormale — Frenet-Serret: T'=κN, N'=-κT+τB, B'=-τN"),
        ("Superfici",                  "parametrizzazione r(u,v) — prima forma fondamentale gᵢⱼ: misura lunghezze, angoli, aree (dA=|rᵤ×rᵥ|dudv) — metrica intriseca"),
        ("Curvatura di superficie",    "seconda forma fondamentale — curvature principali κ₁,κ₂ — curvatura gaussiana K=κ₁κ₂ — media H=(κ₁+κ₂)/2 — teorema Egregium: K intrinseca"),
        ("Geodetiche",                 "curva di minima lunghezza su superficie — equazione geodetica — geodetiche su sfera = grandi cerchi — parallele sui coni — applicazioni in GPS"),
    ]),
    ("🏛️ TOPOLOGIA", [
        ("Spazi metrici",              "distanza d(x,y): non-neg, d=0↔x=y, simmetria, triangolare — sfera aperta B(x,r) — convergenza, continuità, completezza (Cauchy)"),
        ("Spazi topologici",           "spazio (X,τ): τ famiglia di aperti chiusa per unioni arbitrarie e intersezioni finite — base di topologia — esempi: discreta, indiscreta, euclidea"),
        ("Continuità topologica",      "f continua ↔ preimmagine di aperto è aperto — omeomorfismo: biiettiva, continua, inversa continua — invarianti topologici"),
        ("Compattezza",                "ogni ricoprimento aperto ha sottoricop. finito — in Rⁿ: compatto ↔ chiuso e limitato (Heine-Borel) — immagine continua di compatto è compatta"),
        ("Connessione",                "spazio non separabile in due aperti disgiunti non vuoti — connessione per archi (più forte) — componenti connesse — invariante topologico"),
        ("Gruppo fondamentale",        "π₁(X,x₀): cappi in x₀ modulo omotopia — semplicemente connesso se π₁ triviale — sfera vs toro — rivestimenti — teorema di van Kampen"),
        ("Superfici e classificazione","ogni superficie compatta orientabile ↔ sfera con g manici (genere g) — caratteristica di Eulero χ=2-2g — nastro di Möbius non orientabile"),
    ]),
    ("📐 ALGEBRA LINEARE AVANZATA", [
        ("Spazi vettoriali astratti",  "assiomi spazio vettoriale su campo F — sottospazio, somma, intersezione — dimensione, base, teorema della base — Grassmann: dim(U+V)=dim U+dim V-dim(U∩V)"),
        ("Trasformazioni lineari",     "T:V→W lineare: T(αu+βv)=αT(u)+βT(v) — nucleo ker T e immagine im T — teorema rank-nullity: dim(ker T)+dim(im T)=dim V"),
        ("Prodotto scalare e Gram-Schmidt","prodotto scalare ⟨x,y⟩ — ortogonalità, norma — Gram-Schmidt: da base qualsiasi a base ortonormale — spazio di Hilbert (completezza)"),
        ("Proiezioni e minimi quadrati","proiez. ortog. proj_W v=Σ⟨v,eᵢ⟩eᵢ — pseudoinversa Moore-Penrose A⁺ — minimi quadrati: Ax=b → x=(AᵀA)⁻¹Aᵀb — regressione lineare"),
        ("Decomposizione LU e QR",     "LU: A=LU per eliminazione gaussiana, risolvi Ly=b poi Ux=y — QR: A=QR con Q ortogonale, R triangolare — Householder, Gram-Schmidt — O(n³)"),
        ("SVD — Singular Value Decomp.","A=UΣVᵀ — valori singolari σᵢ — rango = numero σᵢ>0 — norma ‖A‖₂=σ₁ — compressione immagini, PCA, pseudoinversa — calcolo con iterazione di potenza"),
        ("Forme quadratiche",          "q(x)=xᵀAx con A simmetrica — teorema spettrale: A=QΛQᵀ — definita positiva se tutti λᵢ>0 — segnatura — classificazione coniche e quadriche"),
    ]),
    ("🔬 ALGEBRA ASTRATTA", [
        ("Teoria degli insiemi",       "assiomi ZFC — operazioni: ∪,∩,\\,× — relazioni — funzioni iniettive/suriettive/biettive — cardinalità: |N|=ℵ₀, |R|=ℵ₁ — teorema di Cantor"),
        ("Induzione matematica",       "principio di induzione: P(1) vera + P(k)⟹P(k+1) → P(n) vera ∀n — induzione forte — principio del buon ordinamento — esempi: Σi=n(n+1)/2"),
        ("Gruppi",                     "(G,·): chiusura, associatività, identità e, inverso — gruppo di ordine |G| — abeliano — esempi: Z, Zₙ, Sₙ, GL(n), gruppi di simmetria"),
        ("Sottogruppi e Lagrange",     "H≤G sottogruppo: chiuso, identità, inversi — classi laterali — teorema di Lagrange: |H| divide |G| — indice [G:H]=|G|/|H|"),
        ("Omomorfismi e quoziente",    "φ:G→H omomorfismo: φ(ab)=φ(a)φ(b) — ker φ e im φ — teorema isomorfismo: G/ker φ≅im φ — gruppo quoziente G/N con N normale"),
        ("Anelli e campi",             "anello (R,+,·): due operazioni, distributività — ideale, anello quoziente — campo: anello con unità e tutti gli elementi invertibili — Q, R, C, Z_p"),
        ("Polinomi e fattorizzazione", "anello K[x] — divisione euclidea, MCD, teorema di Ruffini — fattorizzazione su Q: criterio di Eisenstein — polinomio irriducibile su K"),
        ("Teoria di Galois (intro)",   "estensione di campi K⊆L — gruppo di Galois Gal(L/K) — corrispondenza di Galois — risolvibilità per radicali: quintici in generale irrisolvibili"),
    ]),
    ("🎲 PROBABILITÀ AVANZATA", [
        ("Spazio di probabilità",      "(Ω,F,P): spazio campionario, σ-algebra, misura P — eventi indipendenti P(A∩B)=P(A)P(B) — probabilità condizionata P(A|B)=P(A∩B)/P(B)"),
        ("Var. aleatorie discrete",    "variabile aleatoria discreta X, PMF P(X=x) — valore atteso E[X]=Σx·P(X=x) — varianza Var(X)=E[X²]-E[X]² — Bernoulli, Binomiale, Poisson, Geometrica"),
        ("Var. aleatorie continue",    "PDF f(x), CDF F(x)=∫f — E[X]=∫xf(x)dx — normale N(μ,σ²), esponenziale λe^(-λx), uniforme — cambio variabile con Jacobiano"),
        ("Teorema centrale limite",    "TCL: (X̄-μ)/(σ/√n)→N(0,1) in distribuzione — converge per n→∞ — base di tutta la statistica inferenziale — errore standard σ/√n"),
        ("Legge dei grandi numeri",    "LGN forte: X̄→μ quasi certamente — LGN debole: in probabilità — frequenza relativa converge a probabilità — disuguaglianza di Chebyshev"),
        ("Catene di Markov",           "processo Markov: P(Xₙ₊₁|X₀,...,Xₙ)=P(Xₙ₊₁|Xₙ) — matrice di transizione P — distribuzione stazionaria πP=π — ergodicità — PageRank"),
        ("Processi stocastici",        "processo di Wiener (moto browniano): W(0)=0, incrementi indipendenti gaussiani, W(t)-W(s)~N(0,t-s) — lemma di Itô — Black-Scholes"),
    ]),
    ("📊 STATISTICA AVANZATA", [
        ("Stima statistica",           "stimatore θ̂ — non distorto: E[θ̂]=θ — efficienza: minima varianza — MLE: massimizza L(θ)=∏f(xᵢ|θ) — metodo dei momenti"),
        ("Intervalli di confidenza",   "IC 95%: X̄±1.96σ/√n (nota σ) — t di Student (campioni piccoli, σ ignota) — chi-quadro per varianze — interpretazione: non è P(θ∈IC)=0.95"),
        ("Test di ipotesi",            "H₀ (nulla) vs H₁ (alternativa) — errore tipo I (falso positivo) α, tipo II (falso negativo) β — p-value — potenza — dimensione campione"),
        ("Test parametrici",           "z-test, t-test (un campione, due campioni, appaiato) — F-test — ANOVA un fattore e a due vie — assunzioni: normalità, omoschedasticità"),
        ("Test non parametrici",       "Mann-Whitney U, Kruskal-Wallis, test di Wilcoxon — chi-quadro di indipendenza e bontà d'adattamento — Spearman — quando usarli"),
        ("Regressione",                "regressione lineare: y=β₀+β₁x — OLS: minimizza Σ(yᵢ-ŷᵢ)² — R², F-test, t-test coefficienti — residui — regressione multipla e logistica"),
        ("Statistica bayesiana",       "P(θ|X)∝P(X|θ)P(θ) — prior, likelihood, posterior — Bayes vs frequentista — MCMC: campionamento Metropolis-Hastings — modelli gerarchici"),
    ]),
    ("🧮 MATEMATICA DISCRETA", [
        ("Logica proposizionale",      "proposizioni, connettivi ∧,∨,¬,→,↔ — tavola di verità — tautologie — forme normali CNF/DNF — risoluzione — SAT problem"),
        ("Logica del primo ordine",    "predicati P(x), quantificatori ∀,∃ — interpretazioni — completezza di Gödel — teoremi di incompletezza di Gödel — decidibilità"),
        ("Teoria degli insiemi formale","ZFC: estensione, coppia, unione, potenza, separazione, sostituzione, infinito, regolarità, scelta — ordinali e cardinali — ℵ₀,ℵ₁,ℶ₀"),
        ("Teoria dei grafi discreta",  "grafi G=(V,E) — alberi: connessi aciclici — bipartiti — planarità (Kuratowski: K₅,K₃₃) — colorazione — teorema dei 4 colori — isomorfismo"),
        ("Relazioni di ricorrenza",    "aₙ=c₁aₙ₋₁+c₂aₙ₋₂ — equazione caratteristica — Fibonacci, Torre di Hanoi T(n)=2T(n-1)+1 — metodo della funzione generatrice"),
        ("Funzioni generatrici",       "G(x)=Σaₙxⁿ — moltiplicazione = convoluzione — calcolo di successioni difficili — partizioni di un intero — metodo Wilf"),
        ("Teoria dei codici",          "codici a rilevazione/correzione errori — distanza di Hamming d(u,v) — peso — codice di Hamming [7,4,3] — Reed-Solomon — codici ciclici"),
    ]),
    ("⚙️ METODI NUMERICI", [
        ("Errori numerici",            "errore assoluto/relativo — cifre significative — aritmetica floating point IEEE 754: mantissa, esponente, overflow, underflow — cancellazione catastrofica"),
        ("Radici di equazioni",        "bisezione: O(log₂((b-a)/ε)) — Newton-Raphson: xₙ₊₁=xₙ-f(xₙ)/f'(xₙ), convergenza quadratica — secante — metodo di Brent robusto"),
        ("Sistemi lineari numerici",   "eliminazione gaussiana con pivoting parziale — fattorizzazione LU — numero di condizione κ(A)=‖A‖·‖A⁻¹‖ — instabilità — metodi iterativi Jacobi, Gauss-Seidel"),
        ("Interpolazione",             "Lagrange: P(x)=Σf(xᵢ)Lᵢ(x) — Newton con differenze divise — spline cubiche (C² raccordate) — errore di interpolazione — fenomeno di Runge"),
        ("Integrazione numerica",      "trapezi: O(h²) — Simpson 1/3: O(h⁴) — Gauss-Legendre: esatta per polinomi grado 2n-1 — quadratura adattiva — stima dell'errore"),
        ("ODE numeriche",              "Eulero esplicito xₙ₊₁=xₙ+hf(xₙ,tₙ): O(h) — Runge-Kutta RK4: O(h⁴) — stabilità — metodi impliciti per ODE rigide — Adams-Bashforth"),
        ("Autovalori numerici",        "metodo delle potenze: converge all'autovalore dominante — deflazione — algoritmo QR: iterazione con shift — Lanczos per matrici grandi e sparse"),
        ("FFT e segnali",              "DFT Xₖ=Σxₙe^(-2πikn/N) — FFT di Cooley-Tukey: O(N log N) invece di O(N²) — finestre: Hann, Hamming — spettro di potenza — zero-padding"),
    ]),
    ("🎯 OTTIMIZZAZIONE", [
        ("Programmazione lineare",     "max cᵀx s.t. Ax≤b, x≥0 — forma standard — vertici del poliedro — simplesso: pivot, tableau — dualità LP — teorema forte: cᵀx*=bᵀy*"),
        ("Programmazione intera",      "variabili intere — NP-difficile in generale — branch & bound — piani di taglio di Gomory — ILP applicazioni: scheduling, bin packing, VRP"),
        ("Ottimizzazione convessa",    "insieme convesso, funzione convessa — minimo locale = globale — condizioni KKT: ∇f=Σλᵢ∇gᵢ — dualità di Lagrange — strong duality"),
        ("Gradient descent",           "xₙ₊₁=xₙ-α∇f(xₙ) — learning rate α — convergenza per funzioni fortemente convesse — momentum, Adam — SGD per ML — saddle points"),
        ("Teoria dei giochi",          "gioco a somma zero: matrice payoff A — strategia mista — equilibrio di Nash: nessun giocatore migliora unilateralmente — teorema minimax von Neumann"),
        ("Ottimizzazione globale",     "problemi non-convessi — simulated annealing — algoritmi genetici — particle swarm — basin-hopping — DIRECT — garanzie teoriche limitate"),
    ]),
    ("♾️ ANALISI FUNZIONALE", [
        ("Spazi di Banach",            "spazio normato completo: Lᵖ, C[a,b], ℓᵖ — completamento — teorema di categoria di Baire — teorema di Hahn-Banach: estensione funzionali"),
        ("Spazi di Hilbert",           "prodotto scalare completo: L²[a,b] — base ortonormale (Schauder) — serie di Fourier in L² — teorema di proiezione — duale = se stesso (Riesz)"),
        ("Operatori lineari limitati", "T:X→Y limitato ↔ continuo — norma operatore ‖T‖=sup_{‖x‖=1}‖Tx‖ — spazio L(X,Y) — operatori compatti — aggiunto T*"),
        ("Spettro di un operatore",    "σ(T)={λ: T-λI non invertibile} — autovalori, spettro continuo e residuo — teorema spettrale per operatori autoaggiunti: A=∫λ dE_λ"),
        ("Teorema del punto fisso",    "Banach-Caccioppoli: contrazioni T su Banach hanno unico punto fisso — Brouwer: continuo su D^n ha punto fisso — Schauder — applicazioni ODE/PDE"),
        ("Distribuzioni",              "distribuzionale T: spazio di test D→R lineare continuo — derivata distribuzionale — δ di Dirac — trasformata di Fourier di δ — funzione di Green"),
    ]),
    ("📏 TEORIA DELLA MISURA", [
        ("σ-algebra e misura",         "σ-algebra F: chiusa per complemento e unioni numerabili — misura μ: F→[0,+∞] σ-additiva — misura di Lebesgue su R — misura prodotto"),
        ("Integrale di Lebesgue",      "integrale di Lebesgue per funzioni misurabili — domina Riemann: se Riemann esiste → Lebesgue uguale — teorema convergenza dominata (Lebesgue)"),
        ("Spazi Lᵖ",                  "Lᵖ(Ω,μ): funzioni con ∫|f|ᵖ dμ<∞ — norma ‖f‖_p — disuguaglianza di Hölder: ‖fg‖₁≤‖f‖_p‖g‖_q con 1/p+1/q=1 — completezza (Riesz-Fischer)"),
        ("Teorema di Radon-Nikodym",   "se ν≪μ (assolutamente continua) allora ∃f≥0: ν(A)=∫_A f dμ — densità di probabilità come derivata di Radon-Nikodym — misure con segno"),
        ("Probabilità come misura",    "spazio probabilità (Ω,F,P) come spazio di misura con P(Ω)=1 — variabile aleatoria = funzione misurabile — valore atteso = integrale di Lebesgue"),
    ]),
]

# ── Sezioni sicurezza aggiuntive (non in SEZIONI_ARGOMENTI) ───────────────────

SEZIONI_SICUREZZA_EXTRA = [
    ("🖥️ VIRTUALIZZAZIONE — Proxmox, VMware, VirtualBox", [
        ("Hypervisor tipo 1 e 2",      "hypervisor tipo 1 (bare-metal): ESXi, Proxmox, Hyper-V — gira direttamente su hardware — tipo 2 (hosted): VirtualBox, VMware Workstation su OS host"),
        ("Proxmox VE",                 "Proxmox Virtual Environment: KVM per VM, LXC per container — web UI su porta 8006 — gestione storage (ZFS, LVM, Ceph), rete, cluster — backup con vzdump"),
        ("VMware ESXi e vSphere",      "ESXi: hypervisor enterprise tipo 1 — vCenter: gestione centralizzata cluster — vMotion: migrazione live VM — DRS, HA — vSAN storage distribuito"),
        ("VirtualBox",                 "VirtualBox: hypervisor tipo 2 open source — snapshot, clonazione — Guest Additions (condivisione cartelle, clipboard) — rete: NAT, bridge, host-only, internal"),
        ("KVM e QEMU",                 "KVM: kernel-based VM integrato in Linux — QEMU: emulatore hardware — virtio: driver paravirtualizzati (10× più veloci) — virt-manager, libvirt, virsh"),
        ("Container vs VM",            "VM: isolamento completo, kernel proprio, GB — container (Docker/LXC): condividono kernel host, MB — namespace e cgroup — sicurezza: VM più forte"),
        ("Reti virtuali",              "vSwitch: switch virtuale — bridge (VM sulla rete fisica), NAT, host-only — VLAN su VM — OVS Open vSwitch — SDN Software Defined Networking"),
        ("Alta disponibilità e HA",    "cluster HA: VM si riavvia automaticamente su altro nodo se nodo muore — fencing (STONITH) — shared storage (Ceph, iSCSI, NFS) — quorum — vMotion live"),
    ]),
]

# ── Sezioni fisica (lista separata) ───────────────────────────────────────────

SEZIONI_FISICA = [
    ("⚙️ MECCANICA CLASSICA — Cinematica e Dinamica", [
        ("Cinematica",                 "cinematica: posizione, velocità v=dx/dt, accelerazione a=dv/dt — moto uniformemente accelerato x=x₀+v₀t+½at² — moto parabolico (gittata)"),
        ("Leggi di Newton",            "1a: inerzia (corpo in quiete/moto rettilineo uniforme se F_netta=0) — 2a: F=ma — 3a: azione-reazione — forza peso P=mg, forze vincolari"),
        ("Lavoro ed energia",          "lavoro W=F·s·cosθ — energia cinetica Ec=½mv² — energia potenziale gravitazionale Ep=mgh — teorema lavoro-energia: W_netto=ΔEc — conservazione"),
        ("Quantità di moto",           "p=mv — impulso J=FΔt=Δp — conservazione della quantità di moto in sistemi isolati — urti elastici (Ec conservata) e anelastici (massa si unisce)"),
        ("Moto circolare e rotazione", "moto circolare: a_c=v²/r=ω²r, F_c=mv²/r — angolare: α=dω/dt, τ=Iα — momento d'inerzia I=Σmᵢrᵢ² — energia rotazionale ½Iω²"),
        ("Gravitazione universale",    "legge di Newton: F=Gm₁m₂/r² — G=6.67×10⁻¹¹ N·m²/kg² — leggi di Keplero: ellissi, aree uguali, T²∝a³ — energia potenziale -GMm/r"),
        ("Corpo rigido e statica",     "equilibrio: ΣF=0 e Στ=0 — centro di massa r_cm=Σmᵢrᵢ/M — teorema di Steiner: I=Icm+Md² — precession gyroscopio — momento angolare L=Iω"),
        ("Oscillazioni e MAS",         "moto armonico semplice: x=A·cos(ωt+φ) — ω=√(k/m) per molla, ω=√(g/L) per pendolo — energia E=½kA² — smorzamento — risonanza ω_r≈ω₀"),
    ]),
    ("🌡️ TERMODINAMICA", [
        ("Temperatura e calore",       "temperatura T (Kelvin), calore Q — capacità termica C=Q/ΔT, calore specifico c — calorimetria Q=mcΔT — calore latente L di fusione/ebollizione"),
        ("Gas ideali",                 "legge gas ideale PV=nRT — R=8.314 J/(mol·K) — legge di Boyle PV=cost, Charles V/T=cost, Gay-Lussac P/T=cost — numero di Avogadro N_A"),
        ("Primo principio",            "1° principio termodinamica: ΔU=Q-W — energia interna U — lavoro W=∫P dV — processi: isotermo (ΔU=0), adiabatico (Q=0), isobaro, isocoro"),
        ("Secondo principio ed entropia","2° principio: calore non fluisce spontaneamente da freddo a caldo — entropia S: ΔS=Q_rev/T ≥ 0 (universo) — irreversibilità — freccia del tempo"),
        ("Macchine termiche e Carnot", "macchina termica: η=W/Q_h=1-Q_c/Q_h — ciclo di Carnot: massima efficienza η_C=1-T_c/T_h — frigorifero: COP=Q_c/W — pompa di calore"),
        ("Gas reali e Van der Waals",  "(P+a/V²)(V-b)=nRT — a: interazioni intermolecolari, b: volume molecolare finito — punto critico — temperatura di Boyle — gas di Van der Waals"),
        ("Termodinamica statistica",   "interpretazione statistica: S=k_B·ln(Ω) — Ω microstati — k_B=1.38×10⁻²³ J/K — distribuzione di Boltzmann p_i∝e^(-Eᵢ/kBT) — funzione di partizione Z"),
    ]),
    ("⚡ ELETTROMAGNETISMO", [
        ("Elettrostatica",             "carica elettrica q, forza di Coulomb F=kq₁q₂/r² (k=9×10⁹ N·m²/C²) — campo E=F/q — flusso Φ=∮E·dA — potenziale V=kq/r — energia U=qV"),
        ("Legge di Gauss",             "∮E·dA=Q_enc/ε₀ — applicazioni: filo infinito E=λ/(2πε₀r), piano E=σ/2ε₀, sfera — ε₀=8.85×10⁻¹² F/m — conduttore: E=0 interno"),
        ("Condensatori e circuiti RC", "condensatore C=Q/V — energia U=½CV² — dielettrici ε=ε₀εᵣ — circuiti RC: carica τ=RC, q(t)=Q(1-e^(-t/τ)) — corrente i=dq/dt"),
        ("Corrente e circuiti",        "corrente I=dq/dt (Ampere) — resistenza R, legge di Ohm V=IR — potenza P=VI=I²R — circuiti serie/parallelo — Kirchhoff KVL e KCL — equivalenti Thevenin"),
        ("Campo magnetico",            "forza di Lorentz F=qv×B — Biot-Savart dB=μ₀I dl×r̂/(4πr²) — filo infinito B=μ₀I/(2πr) — μ₀=4π×10⁻⁷ T·m/A — legge di Ampere ∮B·dl=μ₀I_enc"),
        ("Induzione elettromagnetica", "legge di Faraday: ε=-dΦ_B/dt — legge di Lenz: verso che si oppone alla variazione — induttanza L=Φ/I — circuito RL — trasformatori — generatori"),
        ("Equazioni di Maxwell",       "∇·E=ρ/ε₀, ∇·B=0, ∇×E=-∂B/∂t, ∇×B=μ₀J+μ₀ε₀∂E/∂t — corrente di spostamento — unificano elettricità e magnetismo — prevedono le onde EM"),
        ("Onde elettromagnetiche",     "onde EM: c=1/√(μ₀ε₀)=3×10⁸ m/s — spettro: radio, micro, IR, visibile, UV, X, γ — polarizzazione — irradianza I=P/A — pressione di radiazione"),
    ]),
    ("🌊 ONDE, OTTICA E ACUSTICA", [
        ("Onde meccaniche",            "onda trasversale/longitudinale — y=A·sin(kx-ωt) — velocità v=λf — velocità in corde v=√(T/μ) — onde stazionarie: nodi e ventri — risonanza"),
        ("Effetto Doppler",            "Doppler: f'=f(v±v_o)/(v∓v_s) — sorgente che si avvicina: f'>f — applicazioni: radar, ecografia, spostamento verso il rosso cosmologico — mach number"),
        ("Ottica geometrica",          "riflessione: θᵢ=θᵣ — rifrazione: n₁sinθ₁=n₂sinθ₂ (Snell) — indice di rifrazione n=c/v — riflessione totale interna: θ>θ_c=arcsin(n₂/n₁)"),
        ("Lenti e specchi",            "specchi sferici: 1/f=1/do+1/di — f=R/2 — lenti sottili: 1/f=(n-1)(1/R₁-1/R₂) — ingrandimento m=-di/do — aberrazioni: sferica, cromatica"),
        ("Interferenza e diffrazione", "doppia fenditura Young: Δ=d·sinθ=mλ (max) — film sottili: interferenza con sfasamento λ/2 — diffrazione da singola fenditura — potere risolutivo Rayleigh"),
        ("Polarizzazione",             "luce polarizzata linearmente/circolarmente — legge di Malus: I=I₀cos²θ — polarizzatori incrociati — angolo di Brewster tanθ_B=n₂/n₁ — dicroismo"),
        ("Laser e fotonica",           "laser: pompaggio, inversione di popolazione, emissione stimolata (Einstein A,B) — coerenza — modi di oscillazione — applicazioni: LiDAR, fibra ottica, chirurgia"),
    ]),
    ("💧 MECCANICA DEI FLUIDI", [
        ("Statica dei fluidi",         "pressione P=F/A — legge di Stevino P=P₀+ρgh — vasi comunicanti — barometro — principio di Pascal: pressione si trasmette uguale in tutte le direzioni"),
        ("Principio di Archimede",     "spinta di Archimede F_A=ρ_fluido·V_immerso·g — corpo galleggia se ρ_corpo<ρ_fluido — applicazioni: sottomarini, galleggianti, densitometri"),
        ("Equazione di continuità",    "equazione di continuità: A₁v₁=A₂v₂ (flusso incomprimibile) — portata Q=Av — conservazione della massa — aorta vs capillari"),
        ("Equazione di Bernoulli",     "P+½ρv²+ρgh=cost — tubo di Venturi — effetto Bernoulli: portanza degli aerei — teorema di Torricelli: v=√(2gh) — applicazioni idrauliche"),
        ("Viscosità e flusso",         "viscosità dinamica η — flusso laminare: profilo parabolico — legge di Poiseuille Q=πr⁴ΔP/(8ηL) — numero di Reynolds Re=ρvL/η — turbolenza Re>~2300"),
        ("Onde nei fluidi",            "velocità del suono in gas v=√(γP/ρ)=√(γRT/M) — in acqua ~1480 m/s — onde di pressione — shock wave — cavitazione — applicazioni ultrasuoni"),
    ]),
    ("⚛️ FISICA MODERNA E RELATIVITÀ", [
        ("Relatività ristretta",       "postulati Einstein: c costante in tutti i sistemi inerziali — dilatazione del tempo Δt'=γΔt₀ — contrazione delle lunghezze L'=L₀/γ — γ=1/√(1-v²/c²)"),
        ("Massa-energia",              "E=mc² — energia totale E=γmc² — energia cinetica Ek=(γ-1)mc² — massa relativistica — urti relativistici — fotone: E=hf, p=h/λ, m=0"),
        ("Relatività generale",        "principio di equivalenza: gravità=accelerazione — spazio-tempo curvo — geodetiche — lensing gravitazionale — onde gravitazionali — buchi neri Schwarzschild"),
        ("Effetto fotoelettrico",       "Einstein 1905: E_fotone=hf, energia di estrazione φ — E_cinetica_max=hf-φ — h=6.63×10⁻³⁴ J·s — prove che la luce è quantizzata — Nobel 1921"),
        ("Dualità onda-particella",    "de Broglie: λ=h/p — esperimento di Davisson-Germer (diffrazione elettroni) — principio di indeterminazione ΔxΔp≥ℏ/2 — interpretazione Copenhagen"),
        ("Fisica nucleare",            "nucleo: protoni Z, neutroni N, numero di massa A=Z+N — difetto di massa e energia di legame — radioattività α,β,γ — legge decadimento N=N₀e^(-λt) — T₁/₂"),
        ("Modello Standard",           "fermioni (quark u,d,s,c,b,t e leptoni e,μ,τ,νe,νμ,ντ) e bosoni (γ,W±,Z⁰,g,H) — forze: EM, debole, forte, gravità — QED, QCD — bosone di Higgs 2012"),
    ]),
    ("🌌 MECCANICA QUANTISTICA", [
        ("Equazione di Schrödinger",   "equazione di Schrödinger: iℏ∂Ψ/∂t=ĤΨ — stazionaria: ĤΨ=EΨ — Ψ funzione d'onda — |Ψ|² densità di probabilità — normalizzazione ∫|Ψ|²dV=1"),
        ("Principio di indeterminazione","Heisenberg: ΔxΔpₓ≥ℏ/2, ΔEΔt≥ℏ/2 — ℏ=h/2π=1.055×10⁻³⁴ J·s — non è un limite tecnico ma fondamentale — conseguenze: energia punto zero, tunneling"),
        ("Buca di potenziale",         "buca infinita [0,L]: Ψₙ=√(2/L)·sin(nπx/L) — Eₙ=n²π²ℏ²/(2mL²) — energia quantizzata — buca finita: stati legati e stati liberi — barriera di potenziale"),
        ("Oscillatore armonico QM",    "Ĥ=p²/2m+½mω²x² — Eₙ=(n+½)ℏω — operatori scala a⁺,a — funzioni d'onda: polinomi di Hermite — energia punto zero E₀=½ℏω — applicazioni in QFT"),
        ("Atomo di idrogeno",          "H: Ψₙₗₘ(r,θ,φ)=Rₙₗ(r)Yₗᵐ(θ,φ) — Eₙ=-13.6/n² eV — numeri quantici n,l,m — orbitali s,p,d,f — configurazioni elettroniche — degenerazione"),
        ("Spin e statistiche",         "spin: s=½ per elettrone — stati |↑⟩,|↓⟩ — principio di esclusione di Pauli (fermioni) — statistiche Fermi-Dirac vs Bose-Einstein — condensato BEC"),
        ("Entanglement e QI",          "entanglement: |Ψ⟩=(|↑↓⟩-|↓↑⟩)/√2 — non-separabile — violazione disuguaglianze di Bell — teletrasporto quantistico — crittografia quantistica QKD"),
    ]),
    ("📊 FISICA STATISTICA", [
        ("Maxwell-Boltzmann",          "distribuzione velocità: f(v)=4π(m/2πkT)^(3/2)v²e^(-mv²/2kT) — velocità più probabile v_p=√(2kT/m), media v̄=√(8kT/πm), rms v_rms=√(3kT/m)"),
        ("Ensemble statistici",        "microcanonico (E,V,N fissi) — canonico (T,V,N fissi): Z=Σe^(-Eᵢ/kT) — gran canonico (T,V,μ fissi): Ξ — F=-kT·ln Z — valor medio ⟨E⟩=-∂lnZ/∂β"),
        ("Entropia statistica",        "Boltzmann: S=k_B·ln Ω — Gibbs: S=-k_B Σ pᵢ ln pᵢ — teorema H di Boltzmann — entropia di mescolamento ΔS_mix=-nR Σ xᵢ ln xᵢ"),
        ("Fermi-Dirac e Bose-Einstein","fermioni: n(E)=1/(e^((E-μ)/kT)+1) — bosoni: n(E)=1/(e^((E-μ)/kT)-1) — gas di Fermi: pressione a T=0 — condensato BEC: tutti nello stato fondamentale"),
        ("Transizioni di fase",        "transizioni 1° ordine (calore latente, discontinuità) vs 2° ordine (continue) — parametro d'ordine — esponenti critici — modello di Ising — gruppo di rinormalizzazione"),
        ("Fluttuazioni e rumore",      "teorema di fluttuazione-dissipazione — rumore Johnson-Nyquist: ⟨V²⟩=4kTRΔf — moto browniano — equazione di Langevin — diffusione D=kT/6πηr (Stokes-Einstein)"),
    ]),
    ("🔭 ASTROFISICA E COSMOLOGIA", [
        ("Leggi di Keplero",           "1a: orbite ellittiche con Sole in un fuoco — 2a: aree uguali in tempi uguali (L=cost) — 3a: T²=4π²a³/(GM) — velocità orbitale v=√(GM/r) — velocità di fuga"),
        ("Stelle e ciclo stellare",    "sequenza principale — diagramma HR: luminosità vs temperatura — fusione nucleare H→He (pp-chain, CNO) — gigante rossa, nana bianca, supernova, pulsar, buco nero"),
        ("Buchi neri",                 "raggio di Schwarzschild R_s=2GM/c² — orizzonte degli eventi — singolarità — buchi neri di Kerr (rotanti) — radiazione di Hawking T_H=ℏc³/(8πGMk_B)"),
        ("Big Bang e nucleosintesi",   "modello cosmologico standard — CMB (T=2.725 K, scoperto 1964) — nucleosintesi primordiale (H, He, Li) — epoche: Planck, inflazione, quark, leptoni, fotoni"),
        ("Espansione dell'universo",   "legge di Hubble v=H₀d — H₀≈70 km/s/Mpc — espansione accelerata — equazione di Friedmann — parametro Ω — flat universe Ω_tot=1"),
        ("Materia e energia oscura",   "materia oscura (27%): non interagisce con EM, evidenza: curve di rotazione galassie, lensing — energia oscura (68%): pressione negativa — equazione di stato w=-1"),
        ("Fisica delle stelle di neutroni","dopo supernova: nucleo ρ~10¹⁷ kg/m³ — pressione di degenerazione dei neutroni — massa max Oppenheimer-Volkoff ~3M_☉ — pulsar: rotazione + campo B — magnetar"),
    ]),
    ("💎 FISICA DELLO STATO SOLIDO", [
        ("Struttura cristallina",      "reticoli di Bravais (14 in 3D) — base e cella unitaria — indici di Miller — raggi X e diffrazione: legge di Bragg 2d·sinθ=nλ — difetti: vacanze, interstiziali, dislocazioni"),
        ("Bande energetiche",          "elettroni in potenziale periodico — bande di valenza e conduzione — gap energetico E_g — conduttori (gap=0), semiconduttori (gap piccolo), isolanti (gap grande)"),
        ("Semiconduttori",             "semiconduttori intrinseci (Si, Ge) — drogaggio n (donors: P, As) e p (acceptors: B) — giunzione p-n — diodo — transistor BJT e MOSFET — legge di massa: np=nᵢ²"),
        ("Superconduttività",          "resistenza R=0 sotto T_c — effetto Meissner: B=0 interno — tipo I e tipo II — teoria BCS: coppie di Cooper — applicazioni: MRI, magneti LHC, qubit"),
        ("Magnetismo",                 "diamagnetismo: χ<0 — paramagnetismo: χ>0, legge di Curie χ=C/T — ferromagnetismo: T<T_C, domini, isteresi — antiferro e ferrimagnetismo"),
        ("Effetto Hall",               "effetto Hall classico: R_H=1/ne — effetto Hall quantistico intero (QHE): σ_xy=ne²/h — QHE frazionario (FQHE): quasi-particelle frazionate — applicazioni metrologia"),
    ]),
    ("🔬 BIOFISICA E FISICA APPLICATA", [
        ("Fisica medica",              "raggi X diagnostici (mammografia, TC) — dosimetria: Gray [Gy]=J/kg, Sievert [Sv] — radioterapia — MRI: Larmor f=γB₀/(2π) — PET: positroni e annichilazione"),
        ("Ottica e microscopia",       "microscopio ottico: ingrandimento e risoluzione λ/(2NA) — microscopia a fluorescenza — STED, STORM (super-risoluzione) — AFM e STM (nanometrico)"),
        ("Fisica delle membrane",      "membrana cellulare: doppio strato lipidico — potenziale di membrana -70 mV — equazione di Goldman — modello di Hodgkin-Huxley per potenziale d'azione"),
        ("Biofisica molecolare",       "forze di van der Waals — legame idrogeno — idrofobicità — DNA come polimero — worm-like chain — singola molecola (optical tweezers, patch clamp)"),
        ("Fisica dei plasmi",          "plasma: gas ionizzato — frequenza di plasma ω_p=√(ne²/ε₀m) — fusione nucleare (ITER, NIF) — confinamento magnetico: tokamak — instabilità di Kelvin-Helmholtz"),
        ("Simulazioni fisiche",        "simulazione numerica: differenze finite per equazione del calore — metodo Monte Carlo: integrazione multidimensionale — molecolare dynamics — lattice Boltzmann per fluidi"),
    ]),
]

# ── Sezioni chimica (lista separata) ──────────────────────────────────────────

SEZIONI_CHIMICA = [
    ("⚗️ CHIMICA GENERALE E STRUTTURA ATOMICA", [
        ("Struttura atomica",          "modelli atomici: Thomson (plum pudding), Rutherford (nucleo), Bohr (orbite quantizzate), Schrödinger (orbitali) — numero atomico Z, massa A, isotopi"),
        ("Tavola periodica",           "elementi ordinati per Z — periodi (righe) e gruppi (colonne) — proprietà periodiche: raggio atomico, elettronegatività (Pauling), energia di ionizzazione, affinità elettronica"),
        ("Legami chimici",             "legame ionico: trasferimento e⁻ (ΔEN>1.7) — covalente: condivisione e⁻ — metallico: sea of electrons — van der Waals, legame idrogeno — VSEPR per geometria"),
        ("Nomenclatura IUPAC",         "nomenclatura sistematica: ossidi (MO), idrossidi (M(OH)n), acidi ossigenati, sali — composti organici: suffissi -ano, -ene, -ino, -olo, -ale, -one, -oico, -ammina"),
        ("Stechiometria",              "bilanciamento: coefficienti stechiometrici — mole n=m/M — reagente limitante — resa percentuale — calcoli stechiometrici — titolazione: n_A·M_A·V_A=n_B·M_B·V_B"),
        ("Stati della materia",        "solido (reticolo cristallino), liquido (molecole vicine ma mobili), gas (molecole lontane, PV=nRT) — plasma — transizioni: fusione, ebollizione, sublimazione"),
        ("Soluzioni e concentrazione", "molarità M=mol/L, molalità m=mol/kg, % massa, ppm — proprietà colligative: ΔP, ΔTeb, ΔTf, pressione osmotica π=MRT — legge di Raoult"),
    ]),
    ("🧪 CHIMICA INORGANICA", [
        ("Acidi e basi",               "Arrhenius (H⁺/OH⁻), Brønsted-Lowry (donatore/accettore H⁺), Lewis (accettore/donatore coppia e⁻) — coppie coniugate — forza acida Ka, Kb"),
        ("pH e soluzioni tampone",     "pH=-log[H⁺] — pOH=14-pH — acido forte HCl: pH=-log[HA] — debole: pH=½(pKa-log[HA]) — tampone Henderson-Hasselbalch: pH=pKa+log([A⁻]/[HA])"),
        ("Reazioni di precipitazione", "prodotto di solubilità Ksp=[M^n+][X^m-] — Q vs Ksp — precipitazione: Q>Ksp — effetto dello ione comune — solubilità in acidi e basi — analisi gravimetrica"),
        ("Composti di coordinazione",  "complessi: ione centrale (metallo transizione) + ligandi (Lewis base) — numero di coordinazione — isomeria geometrica (cis-trans) — teoria del campo cristallino"),
        ("Metalli di transizione",     "configurazioni d — proprietà: colorazione (transizioni d→d), paramagnetismo (e⁻ spaiati), attività catalitica — ossidi di Fe, Cu, Cr — acciaio e leghe"),
        ("Chimica dei non-metalli",    "alogeni F₂,Cl₂,Br₂,I₂: reattività decrescente — acidi alogenidrici — ossiacidi del cloro (HClO₄ forte) — zolfo S: H₂S, SO₂, H₂SO₄ — azoto: NH₃, NO, HNO₃"),
        ("Elettrochimica inorganica",  "potenziale standard E° — serie elettrochimica — corrosione: ossidazione del ferro, protezione catodica — galvanoplastica — celle elettrolitiche"),
    ]),
    ("🧬 CHIMICA ORGANICA", [
        ("Idrocarburi",                "alcani CₙH₂ₙ₊₂ (sp³) — alcheni CₙH₂ₙ (sp², doppio legame) — alchini CₙH₂ₙ₋₂ (sp) — aromatici (benzene, regola 4n+2 di Hückel) — cicloalcani"),
        ("Gruppi funzionali",          "alcoli -OH — aldeidi -CHO — chetoni C=O — acidi carbossilici -COOH (Ka) — esteri -COO- — ammine -NH₂ — amidi -CONH- — eteri -O- — nitrili -CN"),
        ("Isomeria",                   "isomeria costituzionale (diversa connettività) — stereoisomeria: geometrica (cis-trans in alcheni), ottica (carbonio chirale, enantiomeri, diastereoisomeri, polarimetria)"),
        ("Meccanismi SN e E",          "SN2: attacco posteriore, inversione Walden, bimolecolare, un passo — SN1: carbocatione, racemizzazione, monomolecolare — E2: antiperiplanare — E1: elimina dopo ionizzazione"),
        ("Reazioni di addizione",      "addizione elettrofila ad alcheni: HX (Markovnikov), H₂ (idrogenazione catalitica Pd), H₂O (idratazione), alogeni Br₂ (anti) — addizione nucleofila a carbonile"),
        ("Chimica aromatica",          "sostituzione aromatica elettrofila: nitrazione (HNO₃/H₂SO₄), alogenazione (Br₂/FeBr₃), Friedel-Crafts — attivatori (OH,NR₂) e disattivatori (NO₂,COOH) — orientazione orto/para vs meta"),
        ("Polimeri",                   "polimeri di addizione: PE (etilene), PP, PVC, PS — polimerizzazione radicalica, anionica, cationica — polimeri di condensazione: nylon (PA), PET, bakelit — Tg e Tm"),
    ]),
    ("🔬 BIOCHIMICA", [
        ("Aminoacidi e proteine",      "20 aminoacidi: chirale L, gruppo R (non-pol, pol, acido, basico) — legame peptidico: condensazione α-COOH+α-NH₂ — struttura 1°,2° (α-elica, β-foglietto), 3°, 4°"),
        ("Enzimi e catalisi",          "enzimi: biocatalizzatori proteici — sito attivo — specificità — cinetica di Michaelis-Menten: v=Vmax[S]/(Km+[S]) — inibitori competitivi, non-competitivi — coenzimi"),
        ("Carboidrati",                "monosaccaridi: glucosio C₆H₁₂O₆ (D-aldoesoso), fruttosio, galattosio — disaccaridi: saccarosio, lattosio, maltosio — polisaccaridi: amido, glicogeno, cellulosa (β-1,4)"),
        ("Lipidi e membrane",          "acidi grassi saturi vs insaturi — trigliceridi — fosfolipidi: doppio strato (testa idrofila, code idrofobe) — colesterolo — segnalazione lipidica — raft lipidici"),
        ("Acidi nucleici DNA RNA",     "basi: purine (A,G), pirimidine (C,T,U) — nucleotide = base+zucchero+fosfato — doppia elica Watson-Crick (antiparallela, A-T 2 H-bond, G-C 3) — RNA: mRNA, tRNA, rRNA"),
        ("Metabolismo energetico",     "glicolisi: glucosio→2 piruvato (+2 ATP, +2 NADH) — ciclo di Krebs: +2 ATP, +8 NADH, +2 FADH₂ — catena respiratoria: NADH→2.5 ATP — totale ~30 ATP per glucosio"),
        ("Biologia molecolare",        "replicazione DNA: DNA polimerasi, primer RNA, Okazaki — trascrizione: RNA polimerasi, promotori, terminatori — traduzione: codoni, anticodoni, ribosomi, chaperon"),
    ]),
    ("⚡ CHIMICA FISICA E TERMODINAMICA CHIMICA", [
        ("Termochimica",               "entalpia di reazione ΔH°rxn=ΣΔH°f(prod)-ΣΔH°f(reag) — legge di Hess — energia di legame — ΔU vs ΔH: ΔH=ΔU+ΔngasRT — calorimetria a bomba"),
        ("Entropia e energia libera",  "ΔS°rxn: positivo se gas aumenta — entropia assoluta 3° principio T=0K — energia libera di Gibbs ΔG=ΔH-TΔS — spontanea se ΔG<0 — dipendenza da T e P"),
        ("Equilibrio chimico",         "costante equilibrio Kc=[prod]^ν/[reag]^ν — Kp=Kc(RT)^Δn — ΔG°=-RT·ln K — Q vs K — principio di Le Chatelier: T,P,concentrazione — equilibrio eterogeneo"),
        ("Cinetica chimica",           "velocità r=k[A]^α[B]^β — ordine di reazione — leggi integrate: 0°,1°,2° — t₁/₂ — Arrhenius k=A·e^(-Ea/RT) — catalisi omogenea/eterogenea — stato di transizione"),
        ("Elettrochimica",             "cella di Daniell — potenziale di cella E°=E°catodo-E°anodo — equazione di Nernst E=E°-(RT/nF)ln Q — ΔG=-nFE° — pH con elettrodo — elettrolisi: leggi di Faraday"),
        ("Spettroscopia chimica",      "IR: stretching/bending, frequenza ν=1/(2π)√(k/μ) — NMR: chemical shift δ(ppm), accoppiamento J — UV-Vis: transizioni π→π*, n→π* — spettrometria di massa: m/z"),
        ("Teoria del legame",          "teoria valenza-shell (VB) vs orbitali molecolari (MO) — MO leganti e antileganti — ordine di legame — diagrammi MO di O₂ (paramagnetico), NO — teoria del campo dei ligandi"),
    ]),
    ("📊 CHIMICA ANALITICA", [
        ("Titolazioni",                "titolazione acido-base: equivalente punto pH=7 solo se K_a=K_b — indicatori (fenolftaleina pH 8.2-10, metilarancio 3.1-4.4) — titolazione con buffer — retrotitolazione"),
        ("Gravimetria e volumetria",   "precipitazione, filtrazione, essiccazione, pesatura — fattore gravimetrico — volumetria redox: permanganato, dicromato — iodometria — complessometria EDTA"),
        ("Cromatografia",              "GC (gas cromatografia): fase stazionaria colonna, carrier He — HPLC: reversed phase (C18), normal phase — TLC, colonna aperta — fattore di ritenzione Rf — risoluzione R"),
        ("Spettroscopia analitica",    "AAS (assorbimento atomico): fiamma o fornetto grafite — ICP-OES/MS: plasma a induzione — fluorescenza X (XRF) — LIBS — sensibilità e limite di rilevazione LOD"),
        ("Errori e validazione",       "errori sistematici (accuratezza) e casuali (precisione) — media, deviazione standard, RSD% — test di Student e F — linearità, ripetibilità, riproducibilità — LOD, LOQ"),
        ("Chimica ambientale",         "DBO (domanda biologica ossigeno) — COD — metalli pesanti in acqua — inquinanti organici persistenti — analisi aria: PM10, PM2.5, SO₂, NOₓ, O₃ — trattamento acque"),
        ("Elettrochimica analitica",   "potenziometria: elettrodo ISE (ione selettivo), pH — voltammetria (LSV, CV, DPV) — polarografia — amperometria — sensori elettrochimici — stripping analysis"),
    ]),
    ("🏭 CHIMICA DEI MATERIALI E INDUSTRIALE", [
        ("Polimeri e plastica",        "polimerizzazione a catena (radicalica, cationica, anionica, Ziegler-Natta) e a stadi (policondensazione) — MW, PDI — proprietà meccaniche Tg, Tm — elastomeri, termoindurenti"),
        ("Ceramiche e vetri",          "ceramiche ossidiche: Al₂O₃, ZrO₂, SiC — reticolo vetroso SiO₂ (tetraedri collegati) — temperatura di transizione vetrosa — vetri tecnici: borosilicato, float — ceramiche avanzate"),
        ("Nanomateriali",              "nanoparticelle (1-100 nm) — effetti quantistici — carbon nanotube (SWCNT, MWCNT) — grafene (sp², conduttore 2D) — quantum dot — nanoparticelle Au e Ag — applicazioni biomediche"),
        ("Chimica industriale",        "sintesi Haber-Bosch: N₂+3H₂→2NH₃ (Fe catalizzatore, 400°C, 150 atm) — processo Ostwald (HNO₃) — cloro-soda — processo Solvay (Na₂CO₃) — cracking petrolio"),
        ("Batterie e fuel cell",       "batteria Li-ion: LiCoO₂/grafite — E°~3.6V — ciclo di carica/scarica — batteria solida — fuel cell H₂/O₂: ΔG=-237 kJ/mol → V_teorico=1.23V — efficienza vs motori termici"),
        ("Fotovoltaico e solare",      "cella solare: giunzione p-n — effetto fotovoltaico (Einstein 1905) — efficienza teorica Shockley-Queisser ~33% — Si monocristallino, policristallino — perovskiti — efficienza record ~47%"),
        ("Farmaceutica e drug design", "lead compound, SAR (structure-activity relationship) — docking molecolare — ADME (assorbimento, distribuzione, metabolismo, escrezione) — sintesi asimmetrica — biofarmaci"),
    ]),
    ("💻 CHIMICA COMPUTAZIONALE", [
        ("Metodi ab initio",           "Hartree-Fock: campo medio, soluzione SCF — post-HF: MP2, CCSD(T) — base set: STO-3G, 6-31G*, cc-pVTZ — errore di base, errore di correlazione — scaling O(N^4)→O(N^7)"),
        ("DFT — Teoria del Funzionale", "Hohenberg-Kohn: E=E[ρ] — equazioni di Kohn-Sham — funzionali: LDA, GGA (PBE), ibridi (B3LYP) — gap HOMO-LUMO — calcolo frequenze IR, NMR — scaling O(N³)"),
        ("Dinamica molecolare",        "MD: integra F=ma con Verlet o leapfrog — campi di forza (AMBER, CHARMM, GROMOS): termini legame, angolo, torsione, VdW, Coulomb — NVT, NPT ensemble — PME per elettrostatica"),
        ("Docking molecolare",         "docking: pose del ligando nel sito attivo — funzione di scoring: empirica, basata su campi di forza, knowledge-based — AutoDock Vina, Glide — RMSD — virtual screening"),
        ("Chimica quantistica applicata","NMR computazionale: chemical shift con GIAO — spettri IR da frequenze armoniche — stati eccitati: TD-DFT, EOM-CCSD — fotodissociazione — AIMD (ab initio MD)"),
        ("Machine learning in chimica","reti neurali per proprietà molecolari — molecular fingerprint (Morgan, MACCS) — graph neural network — potenziali ML (ANI, SchNet) — generazione molecole con VAE/GAN"),
    ]),
    ("🌱 CHIMICA VERDE E AMBIENTALE", [
        ("12 Principi della chimica verde","Anastas & Warner 1998: prevenzione, atomo efficiency, solventi sicuri, catalisi, energie rinnovabili, degradabilità, monitoraggio in tempo reale — e-factor = scarti/prodotto"),
        ("Solventi verdi",             "solventi ionici — CO₂ supercritico (Tc=31°C, Pc=73 bar) — acqua come solvente — solventi da biomassa — DES (deep eutectic solvents) — solventi bio-based (EtOH, 2-MeTHF)"),
        ("Catalisi sostenibile",       "catalisi enzimatica in sintesi industriale — organocatalisi (non-metallica) — fotoredox catalisi — catalisi eterogenea con metalli abbondanti (Fe,Co,Cu,Ni) vs Pd,Rh,Ru"),
        ("Chimica atmosferica",        "strato di ozono: O₃+hν→O₂+O — catalisi CFC: Cl+O₃→ClO+O₂ — buco ozono — effetto serra: CO₂, CH₄, N₂O, H₂O — smog fotochimico: NOₓ+VOC+hν→O₃"),
        ("Chimica dei polimeri bio",   "biopolimeri: PLA (acido lattico), PHA (batterici), PEF — degradazione idrolisi e fotodegradazione — compostabilità — economia circolare — bioplastiche vs biodegradabili"),
    ]),
]

# ── Costruzione liste finali ───────────────────────────────────────────────────

SEZIONI_PYTHON     = [s for s in SEZIONI_ARGOMENTI
                       if s[0] not in _TITOLI_MATEMATICA and s[0] not in _TITOLI_SICUREZZA]
SEZIONI_MATEMATICA = [s for s in SEZIONI_ARGOMENTI if s[0] in _TITOLI_MATEMATICA] + SEZIONI_MATEMATICA_EXTRA
SEZIONI_SICUREZZA  = [s for s in SEZIONI_ARGOMENTI if s[0] in _TITOLI_SICUREZZA] + SEZIONI_SICUREZZA_EXTRA
# Fisica e Chimica sono liste autonome (già complete)

